- dev/scf/docs/bosh-author.md
- docker images build.
- Fix some markdown linter issues
Is just documentation enhancement, maybe just the grammatical needs to be validated.
> Add link to documentation in fissile, regarding

- .gitlab-ci.yml
- README.md
- dev/scf/docs/bosh-author.md
Fixed remaining items related to the v3-develop branch under the SCF repository.
> Fixed remaining v3-develop accurrences

- .gitlab/pipelines/config/config.sh
- .gitlab/pipelines/stages/cleanup.sh
- .gitlab/pipelines/stages/deploy/deploy_cf_operator.sh
- WORKSPACE
- def.bzl
- dev/cf_operator/BUILD.bazel
- doc/mok_brc.md
Pinned cf-operator using Bazel and updated documentation accordingly.
> Pin cf-operator with Bazel

- deploy/helm/kubecf/assets/operations/buildpacks/set_suse_buildpacks.yaml
This PR intends to fix naming convention for SUSE buildpacks.
> Fixing suse buildpack naming

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
- code-of-conduct.md
Bug and Feature Github templates to help developers and contributors to gather the needed information to start a conversation.
Check issue #19 
N/A
N/A
> GitHub Templates and Contributing Document 

- bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
This is a dummy PR to force trigger CI for #80. Will be closed immediately.
> Add OS switch in UAA pre-start patch

- .gitlab-ci.yml
With this trigger, we can push branches with the `test/` prefix for external PRs and CI will trigger.
> Add test/pr/* to trigger common jobs

- .gitlab/pipelines/stages/deploy/wait_kubecf.sh
- def.bzl
- deploy/helm/kubecf/assets/operations/set_deployment_name.yaml
The instance groups will start respecting the BOSH manifest ordering with update serial.
> Bumped cf-operator that includes update serial

- doc/release/release-template.md
- doc/release/release.md
A draft version of the release process and release template.
A definition of what requires to release on KubeCF and later on to support the automation process.
This PR is linked to #20 issue. 
A draft version v0.0.0-alpha created as a guideline.
N/A
> docs: add release process and release template

- .gitlab/pipelines/runtime/config.sh
- def.bzl
- deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/eirini.yaml
See https://github.com/cloudfoundry-incubator/cf-operator/pull/691
Older versions of `cf-operator` will no longer work.
> Change API group name to 'quarks'

- def.bzl
This fixes issues with failing volume-management pods (though it has no actual impact, as far as we know).
Pulls in fixes for https://github.com/cloudfoundry-incubator/cf-operator/issues/699
- Deployed locally (minikube
- Ran smoke tests (passed)
> def.bzl: Bump cf-operator to v0.4.2-147.gb88e4296

- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Fixes #168.
Ran smoke-tests on a kubecf deployment with Eirini.
> Fixed Eirini app logs

- .gitlab-ci.yml
Bumps the CI docker image version.
Keep up-to-date with the image.
By CI running.
> Bumped CI docker image

- doc/dev/general.md
[#169615069](https://www.pivotaltracker.com/n/projects/2192232/stories/169615069)
- Update cf-operator helm chart URL to the current one in use.
- Add note about potential problems when deleting the kubecf ns
manually, and losing the labelling generated by the cf-operator
webhooks on start.
- Fix YAML lints in the general.md file
Required for cf-operator v1.0 release shipment https://www.pivotaltracker.com/n/projects/2192232/stories/169615069
Deploying operators in Kind, then deleting the generated `kubecf` namespace, then deploying kubecf charts into `kubecf` namespace. This will eventually affect a service that relies on the label in the `kubecf` ns, leading to a deployment that will never finish, because services do not have endpoints.
None
- [ x] Bug fix (non-breaking change which …
> Update general documentation

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
Fixes https://github.com/SUSE/kubecf/issues/145.
This bump includes https://github.com/SUSE/cf-acceptance-tests-release/pull/15, which contains the proper fix by @mook-as.
Ran the `route_services` suite of the CATS locally.
> Bumped cf-acceptance-tests-release to 0.0.7

- .gitlab-ci.yml
- .gitlab/pipelines/stages/tests/cf_acceptance_tests.sh
Adds CATS to run on CI.
CATS is the major acceptance-tests for CF.
By CI itself.
> Add CATS to run on CI

- doc/dev/minikube.md
> Missing backslash

- doc/Contribute.md
- doc/dev/image-naming.md
From the experience of adding the brain test igroup and release,
where I tripped at the beginning.
Extended the contribution section, and added a new doc file explaining the naming scheme use by the docker images, and where the pieces are found in the Chart, and manifest.
Remove a trip hazard for new developers.
Documentation changes, tested that formatting is ok, via pandoc to nroff and pdf.
> Additional documentation about docker image names.

- doc/Contribute.md
Followup to #225 
Rephrase the contribute section. Was lost in the initial PR (not staged).
> Oops. Missing change.

- .github/stale.yml
The PR that introduced the stale plugin didn't run on CI. Once it was merged to master, the linter phase failed.
This PR fixes the linting issues and adds missing punctuation to comments.
CI.
> Fixed linting issues on stale plugin

- def.bzl
- testing/acceptance_tests/BUILD.bazel
- testing/brain_tests/BUILD.bazel
- testing/smoke_tests/BUILD.bazel
This new cf-operator contains bug fixes and includes the move from extended sts to regular sts.
Be up-to-date with cf-operator.
Deployed locally.
> Bumped cf-operator

- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
The port of autoscaler metricsforwarder job is wrong.  Change to correct port
Test manually.
> Modify autoscaler metricsforwarder port

- dev/minikube/def.bzl
This version works with minikube 1.4+.
> Bumped minikube image to v0.1.5

- doc/architecture/decisions/0002-git-commit-messages.md
This PR fixes #125  issue and it covers the need of having solid and consistent commit messages.
More details can be found in ADR _0002-git-commit-messages_.
More details can be found in ADR _0002-git-commit-messages_.
N/A
N/A
> docs: Describes the git commit message approach

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/values.yaml
It includes the fix for app domains that have multiple A records.
> Bumped CATS release to 0.0.9

- def.bzl
Bump the version to 0.2.0 so it can be official released.
Release life cycle.
N/A
N/A
\
> Bump KubeCF to 0.2.0

- .concourse/README.md
- .concourse/post-publish.yaml
- .concourse/post_publish.yaml
Adds the pipeline sources and instructions on how to deploy it.
> Add Concourse post-publish pipeline

- README.md
Extended the toplevel README with a section on requirements.
See https://github.com/SUSE/kubecf/issues/295
Documentation changes. Ran them through pandoc to check syntax. (Learned that pandoc's PDF backend (or the latex) does not like the embedded SVG image at the top).
> Added a requirements section to README.

- WORKSPACE
- def.bzl
- deploy/bundle/BUILD.bazel
- deploy/helm/kubecf/BUILD.bazel
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
Just a couple tiny cleanups
Removes all of the versions from the top level `WORKSPACE` file.
(Also, drops the use of `pidof` in the database container to not trigger AppArmor — that is unrelated.)
Built locally.
> Minor cleanup

- def.bzl
- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/values.yaml
This PR bumps the cf-deployment version to [12.33.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v12.33.0).
It includes regular maintenance updates and also addresses CVEs.
> CF deployment bump to 12.33.0

- doc/release/release.md
The new version of the release flow contains some of the Thulio's ideas supported by the git branch trunk.
The packages are now more accurate and easy to differentiate an official version from an unofficial one by checking the versioning number of each package file.
Plus, it will support the automation through the implementation of a GitHub bot.
N/A
N/A
> docs: Update release flow

- CONTRIBUTING.md
- README.md
- code-of-conduct.md
Change the security and conduct email addresses and webpage links.
To reflect the switch from SUSE  to the CloudFoundry organization.
N/A
N/A
> docs: transfer to upstream repo

- LICENSE
- NOTICE
> Update copyright LICENSE and NOTICE files

- .concourse/pipeline.yaml
- README.md
- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
Moved rotation tests at the end of the pipeline so we can run the already green tests first to check for regressions. Also Added a publish step.
> Concourse pipeline fixes

- README.md
> Suggested new wording for the README

- CONTRIBUTING.md
- README.md
- doc/Contribute.md
Update information about CI 
Our CI moved from GitLab to Concourse. Also, there is a difference on how PRs are tested based on whether it's a branch of this repo or a fork.
We want our contributors to know exactly how PRs are being tested.
> Update CI information in contributing guides and README

- README.md
- doc/dev/general.md
The bucket where we push master artifacts after they pass automated tests has changed. This PR updates docs accordingly.
Up to date docs
> Change the bucket where we publish master build artifacts

- deploy/helm/kubecf/values.yaml
https://github.com/SUSE/cf-acceptance-tests-release/commit/187c3c624e314e63cc5b32164576cce2793a2743
Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>
The cleanup trap hides the exit code in case of failures
> Bump CATs release to get proper exit codes

- .concourse/README.md
There is no need for a full Concourse deployment to run the same steps that the pipeline is running, 
add links to a short how-to that describes how to accomplish that
> Update pipeline docs

- .concourse/pipeline.yaml
> Add resource to track the release branch

- deploy/helm/kubecf/assets/scripts/jobs/postgres/bpm_process.sh
This PR intends to fix an permissions issue in autoscaler db when the pod restarts.
fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/408
CaaSP 4.1 with storage class `cinder`.
> fix: fixing permissions issues for autoscaler db

- def.bzl
Increment cf-operator version in def.bzl file.
> Update cf-operator dependency.

- .concourse/pipeline.yaml
Brain tests are broken on CI, we need to figure it out before running it on CI.
CI is busted.
It has not.
> tmp: disable brain tests on CI

- README.md
Adds status badges for various build/test contexts on README.md
Because sometimes people don't notice the status icon at the top right corner (next to the latest commit hash)
You open the README file and look at the badges
> Add badges for context statuses on README [Fixes #420]

- CONTRIBUTING.md
I am adding some sections related to Github issues and how we are handling (right or wrong) them.
fixes #481 
There's some confusion around labels and queues meaning and also where to start.
N/A
N/A
> doc: add some sections related with Github issues.

- .concourse/pipeline.yaml.gomplate
Possible fix for #558 
Bumps Catapult version to latest
Possible fix for #558 
> Bump Catapult version

- .concourse/kubecf-pool-reconciler.yaml.gomplate
- .concourse/pipeline.yaml.gomplate
Bumps the reconciler pipeline slots to match the available resources. Also enables parallel deploy jobs now that we have more room for tests
WIP as it requires more runs to spot potential issues
> Increase ci capacity

- doc/release/release.md
Add a paragraph explaining when issues should be archived.
The community can understand the release process.
N/A
N/A
> doc: Archive the done issues after each release.

- def.bzl
- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/kubecf/values.yaml
- doc/cf_deployment/bump.md
Fixes #473.
Keep cf-deployment up-to-date.
Locally with smoke and CATS.
> feat: bump cf deployment 12.36

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/auctioneer.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/kubecf/assets/operations/job_moving/move_log_cache.yaml
Just a maintenance PR.
Simplifying the code a bit.
Alongside with the cf-deployment bump to 12.36.
> fix: use $bytes instead of .Files.Get $path

- def.bzl
- deploy/helm/kubecf/assets/operations/azs.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/ops.yaml
- deploy/helm/kubecf/templates/s3-blobstore.yaml
- deploy/helm/kubecf/values.yaml
This PR intends to add support for on-demand external blobstore(AWS S3). Original PR: https://github.com/cloudfoundry-incubator/kubecf/pull/138.
fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/563
Uses the standard ops file provided from cf-deployment to provide this feature.
Locally on `minikube`. Following tests were performed:
- diego with singleton blobstore + smoke tests
- diego with external blobstore + smoke tests + CATs
- eirini with singleton blobstore + smoke tests
- eirini with external blobstore + smoke tests
See attached logs:
[test-results2.tar.gz](https://github.com/cloudfoundry-incubator/kubecf/files/4457457/test-results2.tar.gz)
> feat: Adding support for external blobstore.

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
Logging sidecar is disabled for test errands.
Fixes #620 
Ran locally
> Don't use a logging sidecar for test errands

- doc/external_bobstore.md
This PR intends to add document for using AWS S3 external bobstore configuration with kubecf.
fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/200
Should only be merged after: https://github.com/cloudfoundry-incubator/kubecf/pull/608
We need documented procedure for people on how to use external blobstore with kubecf.
Reviewer must follow the documented procedure and see if it works as expected.
> doc: adding document for external blobstore config

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
- .concourse/tasks/upgrade.yaml
This PR adds a test in the concourse pipeline to test the upgrade from the latest release to the commit under test.
Fixes #535 
We want to catch changes that break upgrades as soon as possible. 
Tried the upgrade from current stable release (v1.0.1) to this branch and failed. This is to be expected because of a breaking bump of cf-operator. 
https://concourse.suse.dev/teams/main/pipelines/dk-kubecf/jobs/upgrade-test/builds/11
Then tried an upgrade from a recent build from master to some newer commit (where upgrade should work). Test is green: https://concourse.suse.dev/teams/main/pipelines/dk-kubecf/jobs/upgrade-test/builds/12
> Add upgrade test

- .concourse/pipeline.yaml.gomplate
- deploy/helm/kubecf/BUILD.bazel
Sets up KubeCF for v2.0.0 release.
There's still this manual step to release KubeCF.
Built the following targets locally:
- //deploy/helm/kubecf:kubecf
- //deploy/bundle:kubecf-bundle
- //deploy/helm/kubecf:release_chart
Asserted that the chart for the correct version:
```yaml
apiVersion: v1
appVersion: v2.0.0
description: A Helm chart for KubeCF
name: kubecf
version: v2.0.0
```
> feat: release v2.0.0 setup

- .concourse/pipeline.yaml.gomplate
Bump Catapult to latest
Fixes issues in test triggers
> Bump catapult version (v2.0.0)

- deploy/helm/kubecf/values.yaml
Cherry-picked commits from the suse-cf-ci-bot to have a single CI run.
> Bump buildpacks and default stemcell

- deploy/bundle/BUILD.bazel
Make bundle target include the imagelist.txt file.
> Make bundle target include the imagelist.txt file

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
Closes #626.
Enabling the `tasks` suite by default will enhance the test coverage we have.
Locally by enabling only the `v3` and `tasks` suites as instructed in the CATS docs.
> feat: enable tasks CATS suite by detault

- doc/release/release-guidelines.md
Guidelines to release KubeCF major and minor releases.
It will allow anyone with release manager permissions to release.
Proceed wrote while releasing 2.0.0 version.
> docs: Add release process for major and minor versions

- deploy/helm/kubecf/BUILD.bazel
Fixing the version on Bazel to v2.1.0
> feat: Setup 2.1.0

- rules/kubecf/image_list.tmpl.rb
Previously, the image list only returned images derived from the `BOSHDeploymentManifest`.  This changes the script to examine all resources rendered by helm (instead of just the BDPL), and for things which may contain images, use resource-kind-specific logic to determine images required.  Note that these other resource types do not contribute to `stemcells`.
Fixes #745
Ran `bazel build //deploy/helm/kubecf:image_list` locally.
> fix: image_list: return non-BDPL images

- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
This PR adds functionality to only update stemcell version if its higher than existing. 
We recently saw issues in `fissile-stemcell-sle` versions not appearing in order in : https://hub.docker.com/repository/docker/splatform/fissile-stemcell-sle
Test pipelines deployed at concourse.suse.dev.
> fix: check for stemcell semver

- deploy/helm/kubecf/templates/ingress.yaml
Fixes #802.
The default value should allow a regular java app to be deployed.
The value of `64m` has been tested by @troytop.
> fix: bump the nginx proxy-body-size to 64m

- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
Fixes buildpack version bump condition.
Fixes issue with buildpack bumps.
concourse.suse.de
> fix: fixing condition for buildpack version bump.

- deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
- deploy/helm/kubecf/values.yaml
Version 0.0.12 of the brain tests include a mechanism to skip tests based on a BOSH property. Bumping this release on KubeCF also introduces the conditional skipping based on some components being enabled or not on KubeCF.
Improving brain tests to make it pass with KubeCF.
Locally.
> feat: bump brain tests to v0.0.12

- .concourse/config.yaml.sample
- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
- .concourse/tasks/upgrade.yaml
We want to try to use gke for ephemeral test clusters instead of EKCP. We hope that this will lead to more stable CI, faster tests and hopefully not cost too much.
Not yet tested. It's a draft PR. Will deploy the pipeline and test it out.
> Refactor pipeline to use gke

- .concourse/tasks/upgrade.sh
Fixes shell linting errors.
The errors were introduced by https://github.com/cloudfoundry-incubator/kubecf/pull/859.
Running shellcheck only.
> fix: shellcheck linting errors

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/values.yaml
> fix: Cherry Pick "Use correct encryption key labels #853"

- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
> fix: Cherry Pick Autoscaler should use internal URL for cloud controller #891"

- .concourse/pipeline.yaml.gomplate
- deploy/bundle/BUILD.bazel
- deploy/helm/kubecf/BUILD.bazel
- deploy/helm/kubecf/values.yaml
- rules/kubecf/BUILD.bazel
- rules/kubecf/create_sample_values.rb
- rules/kubecf/def.bzl
> feat: Cherry Pick "Bundle sample values #857"

- bosh/releases/pre_render_scripts/api/cc_uploader/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cc_uploader_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cloud_controller_api_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_file_server_ctl.sh
- bosh/releases/pre_render_scripts/asdatabase/postgres/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/auctioneer/auctioneer/jobs/patch_auctioneer_ctl.sh
- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_ctl.sh
- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_json.sh
- bosh/releases/pre_render_scripts/diego-api/locket/jobs/patch_locket_ctl.sh
- bosh/releases/pre_render_scripts/diego-cell/cflinuxfs3-rootfs-setup/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_post-start.sh
- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_ctl.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_json.sh
- bosh/releases/pre_render_scripts/diego-cell/sle15-rootfs-setup/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/eirini/opi/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/router/gorouter/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/routing-api/routing-api/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/scheduler/ssh_proxy/jobs/patch_ssh_proxy_ctl.sh
- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/jobs/patch_blobstore_pre-start.sh
- bosh/releases/pre_render_scripts/smoke-tests/smoke_tests/jobs/patch_test.sh
- bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
> fix: Cherry Pick "ensure patches are applied #873"

- .concourse/pipeline.yaml.gomplate
https://github.com/cloudfoundry-incubator/kubecf/issues/883
> Pipeline improvements and fixes

- deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
- deploy/helm/kubecf/values.yaml
> feat: Cherry Pick "bump brain tests to v0.0.12 #858"

- deploy/bundle/BUILD.bazel
- deploy/helm/kubecf/BUILD.bazel
- rules/helm/def.bzl
> fix: Cherry Pick "fix: deploy: move sample values into kubecf chart #917"

- deploy/helm/kubecf/values.yaml
> fix: Cherry Pick "Bump smoke-tests to increase app memory limit #920"

- .concourse/pipeline.yaml.gomplate
Reverts cloudfoundry-incubator/kubecf#913
> Revert "Add cats-internetless suite in experimental jobs"

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/values.yaml
> feat: Cherry Pick "Add suse_default_stack feature flag #960"

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/values.yaml
Reverts cloudfoundry-incubator/kubecf#961
> Revert "feat: Cherry Pick "Add suse_default_stack feature flag #960""

- rules/kubecf/image_list.tmpl.rb
> fix: Cherry Pick "image_list.rb only needs to check 2 feature combinations #965"

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/values.yaml
- rules/kubecf/image_list.tmpl.rb
See #966 
This PR is based on the branch for #970 which should be merged first!
> feat: Cherry Pick "Implement features.suse_default_stack.enabled #966"

- dev/kube/kube-ready-state-check.sh
Following changes have been added:
- adding kernel version check.
- adding max user namespaces check.
- removing privileged pod check.
The kube ready state check script must be updated to reflect recent changes.
The idea is to introduce new required checks and remove unnecessary checks.
Local execution by pointing to a `kubeconfig`.
> feat: updating kube ready state check

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
Reverts cloudfoundry-incubator/kubecf#978 . Merged by mistake.
> Revert "Setup proper dns on gke"

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
Reapplying this (accidentally merged) PR: https://github.com/cloudfoundry-incubator/kubecf/pull/978
needed some more work before merging.
> Setup proper dns on gke

- .concourse/pipeline.yaml.gomplate
Re-applying https://github.com/cloudfoundry-incubator/kubecf/pull/913 .
The reason [we reverted that PR](https://github.com/cloudfoundry-incubator/kubecf/pull/951/files) was that CATs became slow. We found that the catapult bump was causing it. We fixed catapult in the meantime so the PR should be ok to be tried again.
> Cats internetless

- deploy/helm/kubecf/values.yaml
Override cflinuxfs3 to incorporate security fixes - #949
Our current cf-deployment does provide only an older cflinuxfs3 which is missing certain security fixes.
To get these fixes as soon as possible we are overriding the cflinuxfs3 version to the latest one.
Locally with catapult.
> Override cflinuxfs3 to incorporate security fixes

- deploy/helm/kubecf/charts/eirini-extensions/templates/ssh-proxy.yaml
- deploy/helm/kubecf/charts/eirini-extensions/values.yaml
- deploy/helm/kubecf/values.yaml
Problems fixed:
- The eirinifs image didn't start the sshd daemon (https://github.com/SUSE/scf-eirini-ci/commit/75fb413094ff0480cd882136f512785baed53381)
- The ssh-proxy service wasn't accessible from the cf-cli (didn't have an external ip or a loadbalancer ip)
- The launchers in the eirinifs image were missing some environment variables and launchers were not executable (https://github.com/SUSE/scf-eirini-ci/commit/68d91221ad72339164a82e34811584f0430390f7)
Deployed this branch on gke and `cf ssh` works.
Fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/1026
This should fix the rest of the issue in https://github.com/cloudfoundry-incubator/kubecf/issues/1016
(everything other than the extension fix which lives here: https://github.com/SUSE/eirini-ssh/pull/22)
> Use a newer (fixed) eirinifs/bits image and make ssh-proxy svc public

- .concourse/pipeline.yaml.gomplate
Add `release-2.3` branch to the list of branches to be tested, having a pipeline for itself.
To test release 2.3.
Already deployed on the pipeline.
> Add pipeline for release-2.3 branch

- .concourse/README.md
- .concourse/kubecf.yaml
- Expand docs for deploying copies of the kubecf pipeline.
- Explain how to target a specific branch on a pipeline copy.
- Add 2 new s3 buckets (`kubecf-ci-draft`, `kubecf-draft`) for use on pipeline copies. These buckets are copies of the existing ones (public, etc), yet s3 will only keep 1 historical version of each file.
Closes https://github.com/cloudfoundry-incubator/kubecf/issues/1036.
Deploy a pipeline copy, following the instructions https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad.
It successfully uses the `-draft` buckets: https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad/jobs/build-master/builds/4.
> Expand pipeline docs for copies of the pipeline

- dev/linters/yamllint.sh
> Fix linting in CI

- .concourse/kubecf.yaml
If we leave testing PRs open against all branches, it will test PRs against
release branches. Those are:
- ensured to fail, since they don't have the bash-is-beautiful build system for
example
- already being tested correctly in their respective release pipelines
Needed by https://github.com/cloudfoundry-incubator/kubecf/issues/1095
When we added the config option.
> Only test PRs open against master branch

- doc/release/release-guidelines.md
Add docs on creating a new release pipeline for new release branches
Documents the changes needed by https://github.com/cloudfoundry-incubator/kubecf/issues/1095
Followed this process to deploy https://concourse.suse.dev/teams/main/pipelines/kubecf-release-2.3
> Add docs on creating a new release pipeline for new release branches

- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
This is to fix issue https://github.com/cloudfoundry-incubator/kubecf/issues/935
I've tested in local minikube dev env with the following setting in value.yaml:
```
features:
embedded_database:
enabled: false
```
After `bazel run //dev/kubecf:apply` command is launched, no `database` or `database-seeder` pods are created.
```
NAME                        READY   STATUS                  RESTARTS   AGE
adapter-0                   4/4     Running                 0          9h
api-0                       0/15    Init:30/63              18         9h
auctioneer-0                0/4     Init:5/9                18         9h
bosh-dns-6fbdfd6bf5-blwwl   1/1     Running                 0          9h
bosh-dns-6fbdfd6bf5-lsjv2   1/1     Running                 0          9h
cc-worker-0 …
```
> Add the ability to disable the database

- deploy/helm/kubecf/charts/eirini-extensions/Chart.yaml
- deploy/helm/kubecf/charts/eirini-extensions/templates/persi-broker.yaml
- deploy/helm/kubecf/charts/eirini-extensions/templates/ssh-proxy.yaml
- deploy/helm/kubecf/charts/eirini-extensions/values.yaml
- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
- deploy/helm/kubecf/values.yaml
Reverts cloudfoundry-incubator/kubecf#1077
> Revert "Disable/clear storage class setting for eirini persi broker"

- .concourse/pipeline.yaml.gomplate
- rules/kubecf/create_sample_values.rb
- scripts/kubecf-build.sh
- Substitute Bazel with Bash build system for lint & build jobs in the pipeline.
- Use `splatform/catapult` container image instead of `thulioassis/bazel-docker-image` in those jobs.
- Port functionality of `bazel test //deploy/helm/kubecf:values_doc_test` into `make kubecf-build`.
- Only print errors when testing the sample `values.yaml`, to leave `make kubecf-build` output unchanged.
Part of https://github.com/cloudfoundry-incubator/kubecf/issues/1010.
Testing in https://concourse.suse.dev/teams/main/pipelines/kubecf-rmbazel
lint, build, publish should be green in master (maybe publish will fail because the tar is already there). The pr tab is used for updating this PR's github statuses.
Manual tests for the change in testing sample values doc tests have been performed:
- Bazel:
* true …
> CI: Remove Bazel usage from the pipeline and port sample-values test to bash build system

- doc/dev/general.md
The example in the docs should match what the users need to do in reality. They don't want to expose no scheduler service but ssh-proxy instead.
We don't want to confuse people
Looks in a deployed kubecf for the right name of the service
> Fix documentation on nginx ingress installation and ssh-proxy

- dependencies.yaml
Cherry pick shellcheck URL change to 2.2 branch, from https://github.com/cloudfoundry-incubator/kubecf/pull/977
Make linting pass.
Locally, running the linter.
> Cherry pick shellcheck URL fix to 2.2 branch

- deploy/helm/kubecf/templates/ingress.yaml
> fix: remove ingress bare domain

- dependencies.yaml
- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
This is a version that supports log rotation.
> Bump quarks operator to 4.5.13

- dependencies.yaml
This reverts commit 21cc19809f47c99993b1b1637f3a9d3de17ede41, reversing changes made to 046b14ca3acdd326741a4e1ea51afc4e33547814.
> Revert "Merge pull request #1208 from cloudfoundry-incubator/cfcontainerizationbot/bot/cf-operator"

- deploy/helm/kubecf/generate-minions-values.sh
- doc/multi-cluster.md
This pull request provides a doc for the usage of generate-minions-values.sh
https://github.com/cloudfoundry-incubator/kubecf/issues/1166
- [ *] New feature (non-breaking change which adds functionality)
> provide a doc for the usage of generate-minions-values.sh

- .github/workflows/pull-request-ci.yaml
- Makefile
- dev/kube/klog.sh
- scripts/cf-operator-wait.sh
- scripts/kubecf-wait.sh
- scripts/tools/gomplate.sh
- scripts/tools/retry.sh
Based on #1217 with changes to trigger.
> GH Actions with reviews

- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-queue.yaml
This should work for forks as well.
> PR triggering on code review

- doc/architecture/decisions/0004-upgrade-testing.md
Architecture Decision Record for testing upgrades.
We have to ensure that users can upgrade KubeCF deployments.
> ADR for upgrade testing

- chart/assets/operations/instance_groups/database.yaml
fix: https://github.com/cloudfoundry-incubator/kubecf/issues/1250
'toYaml .Values.features.external_database.ca_cert' is multiple lines string, the '|' is added automatically, so don't need the explicit '|'
1. Test with external database with below certs (faked) in values.yml 
```
external_database:
require_ssl: true
ca_cert: |
-----BEGIN CERTIFICATE-----
MIIEZTCCAs2gAwIBAgIQcmIWPjyzmV7KIlkHxqSpDjANBgkqhkiG9w0BAQsFADA8
MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxFDASBgNVBAMM
C3Bvc3RncmVzX2NhMB4XDTIwMDgxMTA3MjU0OFoXDTIxMDgxMTA3MjU0OFowPDEM
MAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MRQwEgYDVQQDDAtw
b3N0Z3Jlc19jYTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMFrf42e
V6E8h2JQcI7rqQZfc2Jc0BQJN41lFghYLc1a1g+JEVWty8KNI9sIiEhTtMRAb6PM …
```
> fix: kubecf#1250: Double vertical bars '|' when interpolate external database CA cert.

- dependencies.yaml
Increment cf-operator version in def.bzl file.
> feat: update cf-operator dependency.

- .gitignore
- Makefile
- chart/assets/operations/instance_groups/diego-cell.yaml
- scripts/cf-operator-delete.sh
Configures the diego cell IG so it doesn't use unnecessary link instances or the REPLICAS env var.
#fixes #981 
Locally scaled from 2 to 4 cells and back.
> fix: cells can be scaled without restarting the entire set

- chart/assets/operations/addons.yaml
- chart/assets/operations/instance_groups/diego-cell.yaml
Fixes logging agents configuration for spec index and IPs, which are not available in BPM yaml rendering.
fixes #407 
fixes #1198
> fix: logging agents configuration

- chart/config/sle15.yaml
- dev/kubecf/README.md
- dev/kubecf/gitignore
> feat: Update SUSE Nginx buildpack to version 1.1.15.1 and bump all other out of date SUSE buildpacks

- doc/rfd/0000/README.md
- doc/rfd/0001/README.md
- doc/rfd/0002/README.md
- doc/rfd/0003/README.md
- doc/rfd/0004/README.md
Add the pull request link from former ADRs into the `discussion` field since they were missing.
Keep all the information tide.
N/A
N/A
- [x ] I have updated the documentation accordingly.
> fix: add the pull request links for each RFD

- mixins/eirini/config/eirini.yaml
- mixins/eirinix/config/eirinix.yaml
- mixins/eirinix/templates/loggregator-bridge.yaml
fixes https://github.com/cloudfoundry-incubator/kubecf/issues/1304 
~~Depends on: https://github.com/cloudfoundry-incubator/eirini-loggregator-bridge/pull/27~~ Merged
~~Needs still changes from loggregator-bridge~~
https://github.com/cloudfoundry-incubator/kubecf/issues/1304
> fix: bump Eirini to 1.8.0.1 which include a sle based image

- .concourse/pipeline.yaml.gomplate
Consumes https://github.com/SUSE/catapult/pull/284.
No other changes introduced by the bump.
Part of https://github.com/cloudfoundry-incubator/kubecf/issues/1007
Locally, checking that the CATS config on Eirini is correct.
Pipeline already flown.
> fix: Bump catapult on CI to configure Eirini CATS with sle15 stack

- chart/config/releases.yaml
to use the SUSE fork with our changes:
https://github.com/SUSE/cf-acceptance-tests/commit/536591ba792785e0090d3a21240a0e818dcf1486
and bump cf cli:
https://github.com/SUSE/cf-acceptance-tests-release/commit/3c01b157d7d912d5b5d5c88457ca5d54d42a7d80
This is part of this story:
https://github.com/cloudfoundry-incubator/kubecf/issues/1007
Run CATs locally on kind using the same setting and cf cli version on kubecf master and Eirini
> fix: bump cats release

- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
The regex in the automatic stemcell was fixed.
The regex was tested locally.
> fix: Fix regex in Concourse stemcell bump pipeline

- dependencies.yaml
Increment cf-operator version in def.bzl file.
> fix: update cf-operator dependency.

- .github/workflows/pull-request-ci.yaml
Disable Brains for now, let's see how the rest do.
> fix: Disable Brains for now on GH A, let's see how the rest do

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
- .concourse/tasks/upgrade.yaml
Remove also the git part from the version of the artifacts.
Publish final artifacts with `v`, e.g: kubecf-v2.4.0.tgz.
Backported fix of upgrade job:
https://github.com/cloudfoundry-incubator/kubecf/pull/1365
https://github.com/cloudfoundry-incubator/kubecf/pull/1393
Fix publish job:
https://concourse.suse.dev/teams/main/pipelines/kubecf-release-2.5/jobs/publish-release-2.5/builds/3
Already flown.
> fix: release-2.5 publish job fix, and backport upgrade job fixes

- .concourse/pipeline.yaml.gomplate
Bump Catapult, fixes upgrade job
Consumes https://github.com/SUSE/catapult/pull/285/files
Fix the upgrade job.
Not tested.
Already flown.
> fix: Bump Catapult, fixes upgrade job

- chart/assets/operations/instance_groups/scheduler.yaml
- mixins/eirini/templates/configmap.yaml
- mixins/eirinix/config/eirinix.yaml
- mixins/eirinix/templates/instance-index-env-injector.yaml
[WIP] The changes have been tested with the latest master of cf-acceptance-tests (our fork): https://github.com/SUSE/cf-acceptance-tests
but the release we use in the PR (0.0.20) doesn't include all the changes in master. There are 9 CATs still failing in Eirini on this branch. We should first fix them then create a new release for our cf-acceptance-tests-release and consume it in this PR to make it ready for review
- [x ] My code follows the code style of this project.
> fix: changes for CATS so they work for both Eirini and Diego

- .concourse/kubecf.yaml
Move cf-acceptance-tests-eirini job to prod tab in Concourse
Well, because Eirini CATS is green.
Already flown.
> feat: Move cf-acceptance-tests-eirini job to prod tab in Concourse

- .concourse/tasks/upgrade.sh
Add dns record for ssh_proxy in upgrade job too.
We forgot it in:
https://github.com/cloudfoundry-incubator/kubecf/pull/1405
Needs to be in master to take effect, nothing to fly.
> fix: Add dns record for ssh_proxy in upgrade job too

- .concourse/tasks/upgrade.sh
Add dns record for ssh_proxy in upgrade job too, in release 2.5 branch.
We forgot it in:
https://github.com/cloudfoundry-incubator/kubecf/pull/1405
Needs to be in master to take effect, nothing to fly.
> Add dns record for ssh_proxy in upgrade job too, in release-2.5 branch

- .concourse/pipeline.yaml.gomplate
Unblocks https://github.com/cloudfoundry-incubator/kubecf/pull/1430.
Tested successfully against https://github.com/cloudfoundry-incubator/kubecf/pull/1430.
Already flown (to be merged directly).
No additional changes on the bump.
> fix: Bump catapult on Concourse CI

- README.md
> fix: update doc links in README

- README.md
> fix: link to the new kubecf docs link

- chart/README.md
- chart/templates/NOTES.txt
- chart/values.yaml
Point all of the remaining kubecf.suse.dev links to kubecf.io, as the old site is currently broken.
> Fix: update the remaining kubecf.suse.dev links

- chart/templates/_stacks.tpl
Updates the job condition like this:
```
jobs:
diego-cell:
cflinuxfs3-rootfs-setup:
condition: (stacks.cflinuxfs3.enabled) && (!features.eirini.enabled && !features.multiple_cluster_mode.control_plane.enabled)
```
Fixes #1458
> fix: Disable cflinuxfs3-rootfs-setup job when the default stack is disabled

- doc/rfd/README.md
- doc/rfd/rfd/0000/README.md
Add the missing RFD 0 to the RFDs table and correct the RFD 0 title.
Fix missing information.
> fix: update the RFD table with RFD 0

- doc/rfd/rfd/0000/README.md
Update RFD-0 with specifics on publishing RFDs.
There is no clear wording on when RFDs enter in effect.
> docs: Update RFD-0 with specifics on publishing RFDs

- .github/workflows/conventional-commits-lint.yml
- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-queue.yaml
Added a `GIT_PAGER: cat` setting to the GHA definitions.
See #1248 
This is untested as of right now. It is unclear how to test it at all.
> fix: Disable interactive paging for git commands.

- scripts/README.md
- scripts/cf-operator-apply.sh
And allow for additional helm arguments being passed in.
> feat: make the cf-operator chart overridable

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Change the user that is initial assigned to both Bugs and Features.
> fix: change the templates assignee.

- dev/kube/klog.sh
Since the `/var/vcap/sys` and `/var/vcap/jobs` directories are mounts to the same volumes across all containers in a pod, only try to get the logs from them once.  This is getting to be an issue as we end up grabbing a *large* amount of logs, making the process take so long that we're getting killed in CI.
Hitting this when working on #1144 — it was killing my log downloads, which means I had problems getting logs to figure out why my CI runs were dying. (Turns out, because we're OOMKilling nginx.)
Fixes #540.
It ran on CI runs (GitHub Actions), which got me logs — enough to figure out why my things were failing.
- The log structure from klog output changed.  This shouldn't be an issue, as (as far as I know) we don't have automation that reads it.
> fix: klog.sh: don't get the same logs repeatedly

- .github/workflows/pull-request-schedule.yaml
Temporarily disable the GitHub Actions scheduler workflow, because the credentials are not correctly set.
I expect to revert this once we get the credentials in place, but that's taking a while.
Notification email once every ten minutes.
N/A
> fix: CI: Disable scheduler

- CONTRIBUTING.md
Some improvements in how we should handle the new issues at the first stage.
To be transparent to the community and to anyone who needs to understand the flow of the project.
By reading it.
> fix: add more information in how to handle new github issues.

- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-queue.yaml
- Added actions to the flow accessing the suse vault (volt).
- Adapted secret access in other actions to match.
See #1047
It has not, not yet.
> fix: switch flows over to usage of suse vault for secrets.
