- deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
This PR fixes the position of the eirini within the instance groups of the cf manifest. Eirini should start before the cloud controller. See also https://github.com/SUSE/scf/pull/2980
This is required for PR https://github.com/cloudfoundry-incubator/cf-operator/pull/649
It has been tested manually by looking at the secret `<name>.with-ops` after the bosh manifest was deployed. We also checked that cf is starting successfully.
> Fixes the position of the eirini within the instance groups of the cf manifest

- deploy/helm/scf/assets/operations/instance_groups/singleton-blobstore.yaml
Currently cf on k8s doesn't support clusters created by [kops](https://github.com/kubernetes/kops) or [gardener](https://gardener.cloud/), because they uses different cidrs (100.64.0.0/10). See also [Dedicated space for carrier-grade NAT deployment](https://en.wikipedia.org/wiki/Private_network#Dedicated_space_for_carrier-grade_NAT_deployment)
Manual test
> Support additional cidrs for k8s clusters

- deploy/helm/scf/assets/operations/instance_groups/eirini.yaml
Using latest eirini release.
Install kubecf with latest cf-operator. Run `cf push` afterwards.
`cf push` is not working. But this is related to https://github.com/cloudfoundry-incubator/cf-operator/issues/648
> Bump Eirini to 0.0.21

- rules/helm/def.bzl
It'll be necessary for using this same rule for generic charts, like the cf-operator. This `aspect` is only used for getting the chart name and chart version to generate the final YAML file name, hence not really necessary to have.
> Removed namespace from rendered helm template

- def.bzl
- dev/scf/BUILD.bazel
- testing/acceptance_tests/BUILD.bazel
- testing/smoke_tests/BUILD.bazel
By removing the global namespace, I broke the build rules that depended on it.
> Reverted the removal of global namespace

- bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
In case a different stemcell is used, for example Ubuntu, some patches are no
longer valid for specific BOSH releases. There was an issue that the patch for
the CA certificate location failed to work on Ubuntu based images.
Initially, we tried to enhance the OS specific patches, by getting the operative
system ID, in order to skip the patch in a non SUSE OS. We realized that this wouldn´t
properly work, while the patch is evaluated under the cf-operator img, which is build
based on openSUSE. We could have try to improve the patch by other means, but this already
looks too complicated, and a feature flag will simplify the desired goal.
Introduce a feature flag called `suse_stemcell`, which adds another ops file to
the list of ops files referenced by the BOSHDeployment CRD.
This would …
> Add OS switch in UAA pre-start patch

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/assets/operations/temporary/cf-acceptance-tests-stemcell.yaml
The bumps the [cf-acceptance-tests-release](https://github.com/SUSE/cf-acceptance-tests-release/) to 0.0.2.
This adds the `cf tail` plugin, which makes many tests pass.
Run CATS locally.
> acceptance-tests: bump to BOSH release 0.0.2

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
The tests expect the endpoint to not include the scheme (`https://`); this is causing some test failures.  Fix that.
Also, drop the logs container for the CATS & smoke tests pods, since they are BOSH errands.  The logs container was pointlessly holding the pods alive (since they never complete).
Ran CATS locally.
> CATS: Fix API endpoint

- def.bzl
The URLs for darwin and windows were incorrect.
> Fixed kubectl URLs on def.bzl

- deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/kubecf/templates/_helpers.tpl
- deploy/helm/kubecf/values.yaml
Allow for a simple change of the stemcell at one spot in the configuration and avoid duplication in configuration.
**Please note:** I realized that different stemcell versions (to be more precise, different fissile versions) were used, for example in `eirini.yaml`, the configured version was `36.g03b4653-30.80-7.0.0_360.g0ec8d681` whereas in the `values.yaml`, it is `36.g03b4653-30.80-7.0.0_340.g2b599a90`. Having only one spot where you define the stemcell version also means that a common fissile version is enforced. However, it looks like there are missing images for some combinations of fissile and BOSH releases, for example when trying to bump to fissile `7.0.0_360.g0ec8d681`.
When trying to switch to another stemcell, there are multiple sections in `kubecf` that need to be modified. …
> Replace hardcoded stemcell settings with template reference

- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
After https://github.com/cloudfoundry-community/eirini-bosh-release/commit/f2856a00bdc234e3437bff61888b5d5df64e4dc4#diff-003fe3ee396141e33a6c6bf3d8e84618, the property `eirini.run_cert_copier` doesn't exist anymore. We have to rely on `eirini.cert_copier_image` now.
Manually watching for the `configure-eirini` errand.
> Fixed property to disable Eirini cert-copier

- .adr-dir
- doc/architecture/decisions/0001-record-architecture-decisions.md
This is a proposal to use [ADRs (Architecture Decision Records)](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) to document architecture decisions of this project.
I proposed that in https://github.com/SUSE/kubecf/issues/125 to properly document a decision about Git commit messages in particular, but it presents a pretty lightweight way to document decisions in general.
We should document architecture decisions made in this project.
It's about process, not software. But it has been tested in the CF community, for example in https://github.com/cloudfoundry/cf-k8s-networking/tree/master/doc/adrs
> Use Architecture Decision Records to make and persist decisions

- deploy/helm/kubecf/templates/ingress.yaml
Removing the whitespace at the end of the conditional ended up with the next line stuck to the previous line, producing invalid YAML.
`bazel run //dev/kubecf:apply` was failing
Deployed again with ingress (on minikube).
> ingress: fix ingress template

- deploy/helm/kubecf/BUILD.bazel
- deploy/helm/kubecf/defs.bzl
- rules/helm/def.bzl
- rules/helm/package.sh
With this change, the bazel helm package stage will inject a new file in the `Metadata.yaml`, with a new key, `operatorChartUrl` with the project defined operator chart url in https://github.com/SUSE/kubecf/blob/3ebba68fbb03fd72df962d67d168a52419c05198/def.bzl#L9.
In this way we don't have to repackage the chart to inject a value in `Chart.yaml`, which is being generated by helm.
We have a reference between the chart generated and the operator version needed to deploy it  #124 
Locally and with Catapult, see https://github.com/SUSE/catapult/pull/76
> Annotate operator chart url in Chart.yaml

- deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/kubecf/values.yaml
Resolves #26
Any idea which docs I should update?
Deployed on kind with this in my values file:
```
kube:
storage_class: custom
```
pvcs were created on the `custom` storageclass (which was not the default)
> Let the user configure the storage class used for components

- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
When a storage class is not provided, we need to remove `/instance_groups/name=<ig>/persistent_disk_type`.
> Fixed storage class when none is provided

- deploy/helm/kubecf/templates/_helpers.tpl
- deploy/helm/kubecf/templates/implicit_vars.yaml
- Added possibility of specifying the name of the implicit var
independently from its path on the Helm values.
- Moved the template definition to the `_helpers.tpl` file.
> Refactored implicit var generation

- def.bzl
This bumps up the minor version of kubernetes from 1.14.6 to 1.15.6.
Housekeeping chore.  This should have no effect on anything.
Ran smoke tests locally (minikube, Linux).
> def.bzl: Bump kube to 1.15.6

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/operations/set_release_versions.yaml
- deploy/helm/kubecf/templates/_helpers.tpl
- deploy/helm/kubecf/values.yaml
Bump cf-acceptance-tests-release to 0.0.6.
We broke running CATS in cf-acceptance-tests-release 0.0.5.
Deployed locally, and checked that CATS starts.
I've fixed the remaining releases that do _not_ use the `kubecf.stemcellLookup` template to now do so.
> Bump CATS release to 0.0.6

- WORKSPACE
- def.bzl
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/templates/single_availability.yaml
- deploy/helm/kubecf/values.yaml
- dev/external_database/BUILD.bazel
- dev/external_database/def.bzl
- dev/external_database/deploy_mysql.sh
- doc/dev/general.md
Adds the external database functionality via Helm values.
Resolves https://github.com/SUSE/kubecf/issues/4.
Using an external database is desired on large setups and on setups that consume managed databases.
The local development and testing was conducted using the provided script for deploying a local mysql database on a separate namespace and deploying kubecf with the example values provided in the updated documentation. The kubecf deployment completed successfully and smoke-tests passed.
> Use external database

- doc/dev/general.md
- doc/dev/minikube.md
The documentation for using the Cloud Foundry CLI to access the
development cluster contains a copy&paste TYPO.
Remove the `-u` and `-p` flags that do not exist in `cf auth …`, but
that exist in `cf login …`.
Followed the development documentation steps to setup a `minikube` based Cloud Foundry.
```
cf auth --help
NAME:
auth - Authenticate non-interactively
USAGE:
cf auth USERNAME PASSWORD
cf auth USERNAME PASSWORD --origin ORIGIN
cf auth CLIENT_ID CLIENT_SECRET --client-credentials
ENVIRONMENT VARIABLES:
CF_USERNAME=user          Authenticating user. Overridden if USERNAME argument is provided.
CF_PASSWORD=password      Password associated with user. Overriden if PASSWORD argument is provided.
WARNING:
Providing your password as a command line option is highly discouraged
Your password …
```
> Fix TYPO in dev docs for Cloud Foundry access

- .gitlab-ci.yml
- WORKSPACE
- def.bzl
- dev/linters/BUILD.bazel
- dev/linters/requirements.txt
- dev/linters/run_yamllint.py
- dev/linters/yamllint.sh
- doc/Contribute.md
- doc/linters.md
This PR adds yaml linting to the dev/ scripts and gitlab, which lints for yaml files, excluding `deploy/helm/kubecf/*`, as those are helm templates that should be better linted with `helm lint`.
To achieve it, it adds a bazel target `//dev/linters:yamllint` to install the yamllint python module, and a python wrapper to call it. I haven't found any other way in Bazel to pull a python module and then call it.
It provides the script `dev/linters/yamllint.sh` that calls the python wrapper. And it updates `.gitlab-ci.yaml` to call this last script.
Bazel's pip_install() doesn't install pip, so this PR needs https://github.com/f0rmiga/bazel-docker-image/pull/3.
I have tested it locally by running `dev/linters/yamllint.sh`.
I have tested it against gitlab-ci by editing the `.gitlab-ci.yaml` to …
> Add yaml linting

- .gitlab/pipelines/runtime/config.sh
- .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/values.yaml
- doc/dev/general.md
- doc/dev/minikube.md
Fixes the ssh-proxy by exposing it via another service similar to the existing router one.
Fixes #146.
The CATS `ssh` suite was failing, pointing out that we were missing its functionality.
Deployed kubecf with the following values:
```
system_domain: kubecf-dev.susecap.net
services:
router:
type: ClusterIP
clusterIP: 10.104.255.1
ssh-proxy:
type: ClusterIP
clusterIP: 10.104.255.2
```
Then ran CATS with only `ssh` suite enabled:
```
properties:
acceptance-tests:
acceptance-tests:
acceptance_tests:
include: '=ssh'
```
- The `service` property on the Helm chart was replaced by `services`, which now allows `router` and `ssh-proxy` to be set.
> Fix ssh-proxy

- bosh/releases/pre_render_scripts/api/routing-api/bpm/patch_bpm.sh
- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
Fixes the `routing-api` IP that is used to register itself to provide `api.((system_domain))/routing`.
The `routing-api` job registers itself via code, and it uses the `-ip` command-line flag for the destination IP. This patch will use the `POD_IP` environment variable that we set via the ops-file, and k8s will render it via https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments.
Got a bash session to the router container and called `/var/vcap/jobs/gorouter/bin/retrieve-local-routes` and checked that the `address` for the `api.((system_domain))/routing` was set to the pod IP. Also, the command `cf router-groups` should succeed (previously failed). The CATS `tcp_routing` suite will eventually test this.
> Fixed routing-api IP that is used to register itself

- .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
- deploy/helm/kubecf/templates/azs.yaml
- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/cf_deployment.yaml
- deploy/helm/kubecf/templates/eirini.yaml
- deploy/helm/kubecf/templates/implicit_vars.yaml
- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/templates/ops-use-bits-service.yaml
- deploy/helm/kubecf/templates/ops.yaml
- deploy/helm/kubecf/templates/properties.yaml
- deploy/helm/kubecf/templates/sizing.yaml
- dev/kubecf/BUILD.bazel
Fixes the cluster-admin role for Eirini. It's now only able to perform operations on the app namespace.
Fixes https://github.com/SUSE/kubecf/issues/175.
Eirini should not be a cluster-admin.
Deployed with Eirini and ran smoke-tests.
> Eirini service account with namespaced role

- def.bzl
- deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/assets/operations/set_deployment_name.yaml
- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/eirini.yaml
- deploy/helm/kubecf/templates/implicit_vars.yaml
- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/values.yaml
- dev/kind/BUILD.bazel
- dev/kind/start.sh
- dev/kubecf/BUILD.bazel
- dev/kubecf/values.yaml
- testing/acceptance_tests/BUILD.bazel
- testing/smoke_tests/BUILD.bazel
We do not need the extra knob, when the helm release name will work just
fine for a unique prefix on the resource names.
Fixes #193
Locally deployed (minikube) and ran smoke tests, though that was before rebasing due to #205.
This is technically breaking, as it changes the admin-visible configs.
The deployment name does not appear to have been previously documented.
> Remove .Values.deployment_name, use helm release name

- dev/minikube/start.sh
- doc/dev/minikube.md
- doc/kube/minikube.md
This lets us pass in extra arguments to minikube (but does not hard code which, since that does not make sense outside of the local context).
I want to set up a local docker registry mirror; this _can_ be done in minikube, but requires extra arguments.  
I now have extra options to use a docker registry mirror on minikube (using @f0rmiga's opensuse image, as is default in kubecf).
> minikube: allow arbitrary extra options

- .gitlab-ci.yml
- dev/linters/BUILD.bazel
- dev/linters/helmlint.sh
- doc/Contribute.md
- doc/linters.md
This adds support for running `helm lint` on the generated chart.
Closes #23 (as this is the last missing linter).
Ran locally.
I could not use `helm lint --strict` as too much of our code relies on accessing unset keys in dictionaries (and expecting them to evaluate to falsy), which is an error with `--strict`.
> Add helm lint support

- .github/stale.yml
GitHub Stale plugin will label issues and pull requests when without activity for more than 60 days and after 7 days it will close them.
To have a lean and meaningful backlog.
N/A
N/A
> mgmt: Add github stale configuration

- deploy/helm/kubecf/templates/brain-tests.yaml
Added the missing namespace to the k8s resources.
The namespace was missing from the brain-tests Role and RoleBinding resources.
It presented problematic on CI.
CI should be able to deploy kubecf.
> Fixed brain tests Role and RoleBinding

- dev/kubecf/.gitignore
The file `dev/kubecf/values.yaml` is currently empty and not needed anymore.
We only had one value in this file before, which was `deployment_name`. Since we removed this property, this file has no use anymore.
N/A.
> Removed dev/kubecf/values.yaml

- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cc_uploader_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cloud_controller_api_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_file_server_ctl.sh
- bosh/releases/pre_render_scripts/database/mysql/jobs/patch_galera-healthcheck_ctl.sh
- bosh/releases/pre_render_scripts/database/mysql/jobs/patch_mariadb_ctl.sh
- bosh/releases/pre_render_scripts/database/mysql/jobs/patch_pre-start-setup.sh
- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_ctl.sh
- bosh/releases/pre_render_scripts/diego-api/locket/jobs/patch_locket_ctl.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_ctl.sh
- bosh/releases/pre_render_scripts/router/gorouter/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/scheduler/auctioneer/jobs/patch_auctioneer_ctl.sh
- bosh/releases/pre_render_scripts/scheduler/ssh_proxy/jobs/patch_ssh_proxy_ctl.sh
- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
Removed all `ulimit` calls to set the open files limit. In some scenarios where the current value is lower than the one being set, it fails. E.g. on EKS, gorouter tries to set the limit to 100000 during the pre-start, while the current value is 65536.
Fixes https://github.com/SUSE/kubecf/issues/250, unblocking QA testing of kubecf on public cloud.
Ran:
```
for pod in $(kubectl get pods --namespace kubecf --output name); do kubectl exec -it --namespace kubecf "${pod#"pod/"}" -- bash -c 'grep --color=auto -r "ulimit" /var/vcap/jobs/'; done
```
and verified that all `ulimit` calls are gone.
> Removed ulimit calls

- WORKSPACE
- def.bzl
- dev/kind/def.bzl
- dev/kind/start.sh
Move a couple downloads (via kube) to be done via bazel.
Move as much network traffic into bazel, so that it can be cached (and in case the network intermittently fails, we might get lucky and end up with it already in cache).  Also, this way we get checksums so that we can know if the download fails / was changed remotely.
`bazel run //dev/kind:start`
> kind/start: don't download files in the script

- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/assets/scripts/jobs/mariadb/bpm_process.sh
- deploy/helm/kubecf/assets/scripts/jobs/postgres/bpm_process.sh
Moving the scripts to shell files, we can lint and have IDE syntax highlighting.
It's weird to have shell scripts indented in YAML as we don't take advantage of syntax highlighting and linting. Whenever possible, we should have shell files and interpolate them using the templating mechanism.
Deployed kubecf and checked that the scripts are working as intended.
> Refactored bpm scripts to be separate shell files

- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
A more appropriate name for the bpm process.
`mariadb_ctrl` -> `mariadb`
A small cleanup in the bpm process.
Deployed kubecf, the name of the container changed.
> Renamed mariadb bpm process

- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
The readiness probe for `bbs` was broken given that it always responded as healthy while not being.
We want the `bbs` readiness probe to respond correctly so that the service endpoints can route to the instance that acquired the lock.
Deployed kubecf and ran CATS.
> Fix the bbs readiness probe

- deploy/helm/kubecf/templates/sizing.yaml
- deploy/helm/kubecf/values.yaml
Fixes https://github.com/SUSE/kubecf/issues/275.
The idea is to remove setting custom sizing for instance groups that are singleton.  
Locally on `minikube`.
> Removing sizing for singleton instance groups

- def.bzl
The kubecf chart versions should be reset.
Kubecf will release version 0.1.0.
CI
> Set chart versions for kubecf

- .drone/pipelines/default/steps/deploy/kubecf.sh
Fixes Drone CI scripts to get it back to business.
With the latest changes for releasing kubecf 0.1.0, Drone CI was left behind on the configuration.
Get Drone CI running.
> Fix Drone CI

- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
The post-start condition was timing out on the `diego-api` passive instance(s) as it was waiting for the instance to become ready.
Since we don't need to wait for the instances to be ready to execute the post-start script, this commit removes the post-start condition.
On every 15 minutes, the passive instance(s) of the `diego-api` would restart due to the post-start timeout set on the `container-run` of cf-operator.
https://github.com/cloudfoundry-incubator/cf-operator/blob/master/container-run/pkg/containerrun/containerrun.go#L20
https://github.com/cloudfoundry-incubator/cf-operator/blob/master/container-run/pkg/containerrun/containerrun.go#L73
Deployed kubecf with 2 instances of the `diego-api` and waited > 15 minutes, asserting that it doesn't restart anymore.
> Fix post-start for diego-api passive instance(s)

- def.bzl
Bump `minikube` version to the latest available one.
The currently configured version of `minikube` in `kubecf` is a bit
outdated and newer versions contain updates to better deal with setup
problems due to VPN or network issues. For example, the current version
just hangs if there is a problem setting up a virtual machine on a macOS
host with `hyperkit` when there is interference with a VPN tool.
Used the respective `bazel` targets to force a minikube installation.
```
bazel run //dev/minikube:start
```
> Bump minikube to v1.6.2

- .drone/pipelines/default/steps/deploy/wait_kubecf.sh
- .gitlab/pipelines/runtime/binaries.sh
- .gitlab/pipelines/stages/deploy/wait_kubecf.sh
- WORKSPACE
- def.bzl
- rules/external_binary/BUILD.bazel
Since `yq` has more options than `yaml2json`, and we introduced it in the project already, this PR removes `yaml2json` completely from the project.
`yaml2json` was introduced in the past to simply convert YAML to JSON, but it's not capable of doing the inverse conversion - JSON to YAML. We then introduced `yq`, but left some usages of `yaml2json` behind.
The scripts using `yaml2json` and `yq` are part of the CI.
> Replaced yaml2json with yq

- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/values.yaml
[GKE] To use a reserved/static IP for LoadBalancer services you need to set `spec.loadBalancerIP`, rather than `spec.externalIPs`. This PR allows the following values to be set for GKE:
```yaml
services:
router:
loadBalancerIP: 34.82.240.78
externalIPs: []
ssh-proxy:
loadBalancerIP: 34.82.240.79
externalIPs: []
tcp-router:
loadBalancerIP: 34.82.240.80
externalIPs: []
```
* against cf-operator v1.0.0
* on GKE
* only for `services.router.loadBalancerIP` to confirm my kube service switched to use my reserved IP
> [GKE] allow setting svc spec.loadBalancerIP for GKE reserved/static IPs

- .drone/deploy/runner/def.bzl
- .drone/deploy/runner/start.sh
- .drone/pipelines/default/steps/deploy/kind.sh
- def.bzl
- dev/kind/start.sh
Adds image registry caches for Drone CI. It reduces the consumed bandwidth for downloading the images while also speeding up the time to deploy the pods.
We want to reduce as much as possible the time spent by the CI pipelines in order to iterate faster on kubecf.
- Assembled all the pieces manually on a local cluster.
- Drone CI will test it.
> Drone registry caches

- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/templates/ingress.yaml
Gorouter listens on port 80, instead of 8000 for its HTTP traffic.
The HTTP traffic on gorouter was not working.
Deployed kubecf, pushed an app and accessed it over the HTTP protocol on port 80.
> Fixed gorouter http target port

- deploy/helm/kubecf/templates/ingress.yaml
Since `tcp-router` will only listen on the TCP port range when it's required, it provides healthcheck on port 80 (default) for upstream load balancers to probe.
Upstream load balancers like the classic AWS ELB require the healthcheck to pass in order to mark the instances as `In Service`.
Deployed kubecf on EKS and verified that the classic ELB marks the instances as `In Service`.
> Exposed the healthcheck port for tcp-router

- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/values.yaml
Operators deploying kubecf can pass arbitrary annotations for each individual service. It's particularly useful to pass cloud provider-specific annotations.
http://web.archive.org/web/20200104141554/https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#aws
Deployed kubecf on EKS with the following annotation:
```yaml
services:
router:
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: nlb
ssh-proxy:
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: nlb
tcp-router:
annotations:
service.beta.kubernetes.io/aws-load-balancer-type: nlb
```
Asserted that the LBs created were of the type Network Load Balancer (NLB).
> Added annotations option for services

- deploy/helm/kubecf/templates/rbac.yaml
- deploy/helm/kubecf/values.yaml
Fixes https://github.com/SUSE/kubecf/issues/306.
By default, KubeCF will create a PSP for its enjoyment, while allowing an existing PSP to be passed via the `kube.psp.default` Helm value. The PSP is then bound to the default service account in the namespace kubecf is installed.
Please, visit https://github.com/SUSE/kubecf/issues/306 for more context.
Deployed on CaaSP 4, which is very restrictive on PSPs.
> Add PSP and default bindings

- WORKSPACE
- def.bzl
- dev/kind/config.yaml
- dev/kind/def.bzl
- dev/kind/start.sh
It enables the use of network policies, especially to block ingress and egress in order to run internetless test suites.
The default CNI plugin used by Kind doesn't allow network policies.
1. From a pod in the default namespace, it succeeded to ping 8.8.8.8.
2. Applied a network policy to block all Ingress and Egress in the default namespace:
```
kubectl apply -f - <<'EOF'                                                                                                               tassis@thulio-laptop
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: block-all
namespace: default
spec:
podSelector: {}
policyTypes:
- Ingress
- Egress
EOF
```
3. From the same pod as step 1, it failed to ping 8.8.8.8.
4. After removing the network policy, it succeeded to ping 8.8.8.8 again.
> Use Weave CNI plugin with Kind

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/temporary/remove_roles.yaml
- deploy/helm/kubecf/values.yaml
- doc/secret_rotation.md
Adds the `rotate-cc-database-key` errand with a mechanism for rotating the CCDB encryption key.
Resolves https://github.com/SUSE/kubecf/issues/203.
CF allows rotating the CCDB encryption key. This PR introduces a mechanism for doing it with kubecf using Helm.
1. Deployed kubecf with:
```yaml
ccdb:
encryption:
rotation:
key_labels:
- encryption_key_0
current_key_label: encryption_key_0
```
2. Ran smoke-tests.
3. Updated kubecf with:
```yaml
ccdb:
encryption:
rotation:
key_labels:
- encryption_key_0
- encryption_key_1
current_key_label: encryption_key_1
```
4. Checked the new encryption key was correctly generated and interpolated in the new desired manifest created by cf-operator.
5. Ran the `rotate-cc-database-key` errand as instructed in the documentation introduced in this very same PR. …
> CCDB encryption key rotation

- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
The log level for the `eirini-loggregator-bridge` extension should be WARN by default, not DEBUG.
The `DEBUG` level is too verbose for production environments (obviously).
Checked that the debugging statements are gone.
> fix: Eirini's loggregator extension in WARN level

- .gitlab/pipelines/stages/publish.sh
Extended the gitlab `publish.sh` script with code to upload the bundle tar archive to a newly made bucket for it and similar transient artifacts.
See https://jira.suse.com/browse/CAP-1029
This is also a follow up to PR #218.
In the gitlab pipeline, see
- https://gitlab.com/susecf/kubecf/pipelines/111546611/builds
- https://gitlab.com/susecf/kubecf/-/jobs/412105734
Note, the tarball uploaded by this test has already been removed from the bucket.
> [jsc#cap-1029] Publish bundles to newly established bucket.

- deploy/helm/kubecf/templates/sizing.yaml
- deploy/helm/kubecf/values.yaml
The log-cache goes wild with memory consumption when it has more than 1 replica. This is a temporary fix.
Please, see https://github.com/SUSE/kubecf/issues/241.
Deployed in HA mode and made sure doppler only got 1 instance. Then ran smoke-tests (which has proven to cause this bug).
> fix: log-cache memory consumption spike

- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Otherwise it assumes the scf deployment is named afterward the release,
not allowing to deploy in different namespaces.
Deploying KubeCF+eirini in a different namespace rather than default would fail with:
```
kube-system kube-controller-manager-kubecf-eirini-master-control-plane kube-controller-manager I0127 10:34:59.061436       1 event.go:221] Event(v1.ObjectReference{Kind:"Job", Namespace:"susecf-scf-eirini", Name:"c2449eae-e00f-4e50-8d99-476a919b5ec4", UID:"af7fd9ed-40ec-11ea-99a3-0242b5c338b0", APIVersion:"batch/v1", ResourceVersion:"8472", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: Internal error occurred: failed calling webhook "0.eirini-ssh.org": Post https://susecf-scf-eirini-ssh.susecf-scf.svc:443/0?timeout=30s: service "susecf-scf-eirini-ssh" not …
```
> Fix Eirini extensions default namespace

- .concourse/post_publish.yaml
Required after https://github.com/SUSE/kubecf/pull/356
Bumps the catapult version which handles the kubecf changes
Pipeline fails in deploying steps
Public concourse pipelines.
Before: https://concourse.suse.dev/teams/main/pipelines/post-publish/jobs/deploy-diego/builds/12
After: https://concourse.suse.dev/teams/main/pipelines/post-publish/jobs/deploy-diego/builds/13
> Bump catapult version in post_publish pipeline

- doc/Contribute.md
- doc/secret_rotation_general.md
New file explaining the process. Further linked pre-existing file for the custom process required by CCDB keys into the new toplevel section.
Added a new section to `doc/Contribute.md`. Added new file containing the bulk of the explanations.
See #44 
Manual testing in a minikube environment.
While the new documentation was added in the developer doc section of the project operators deploying KubeCF are also a proper audience for this information. As such the main product documentation should be extend to contain the same information.
> Documentation explaining the process for general secret rotation

- deploy/helm/kubecf/values.yaml
All the releases(except cf-mysql) must switch over to use SLE15 stemcell based images.
fixes: https://github.com/SUSE/kubecf/issues/373
This is part of transition to use SLE15 everywhere in kubecf instead of opensuse.
CI
> feat: SLE15 stemcell consolidation

- deploy/helm/kubecf/BUILD.bazel
Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>
Fixing the version interpolation (https://concourse.suse.dev/teams/main/pipelines/post-publish/jobs/deploy-eirini/builds/19)
Otherwise deployment fails with, as url aren't interpolated with the version:
```
Error: failed to download "https://cf-operators.s3.amazonaws.com/release/helm-charts/cf-operator-{version}.tgz" (hint: running `helm repo update` may help)
Error: validation failed: unable to recognize "": no matches for kind "BOSHDeployment" in version "quarks.cloudfoundry.org/v1alpha1"
```
> Fix metadata generation for version interpolation

- rules/helm/delete.tmpl.rb
- rules/helm/upgrade.tmpl.rb
Modified the `rules/helm/{delete,upgrade}.tmpl.rb` files to print the generated command (line) just before it is executed.
It should help directly debugging issues with bazel-generated helm commands, and indirectly when comparing a local setup against other environments and the helm command used therein.
Bazel goals making use of the helm rules (Ex `bazel run //dev/cf_operator:apply`) were invoked manually, and confirmed that the generated command is seen in the terminal:
```
...
Target //dev/cf_operator:apply up-to-date:
bazel-bin/dev/cf_operator/apply.rb
INFO: Elapsed time: 0.272s, Critical Path: 0.12s
INFO: 0 processes.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
CMD ["../helm/helm", "upgrade", "cf-operator", …
```
> Feature: Debug support. Print helm commands generated by bazel rules.

- deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
- deploy/helm/kubecf/assets/operations/releases.yaml
- deploy/helm/kubecf/templates/sync-integration-tests.yaml
- deploy/helm/kubecf/values.yaml
- doc/tests.md
- doc/tests_sits.md
- testing/sync_integration_tests/BUILD.bazel
- testing/sync_integration_tests/trigger.yaml
This PR intends to add `sync-integration-tests` instance group and other required components in order to run the tests.
fixes: https://github.com/SUSE/kubecf/issues/120
changes in SITs release: https://github.com/SUSE/sync-integration-tests-release/pull/1
[SITs](https://github.com/cloudfoundry/sync-integration-tests) form an important part of CF test suites as they focus on testing the sync functionality between Cloud Controller and Diego.
This has been tested locally on `minikube`. Please find attached the [logs](https://github.com/SUSE/kubecf/files/4238423/sits.log) from local test execution. There are future plans to add the SITs in pipeline pos-publish concourse pipeline.
> Add SITs instance group

- rules/helm/upgrade.tmpl.rb
[Array#append](https://www.rubydoc.info/stdlib/core/Array#append-instance_method) was added in MRI 2.5.0; use the older name [Array#push](https://www.rubydoc.info/stdlib/core/Array#push-instance_method) instead for better compatibility.
This was reported in [a thread on #kubecf](https://cloudfoundry.slack.com/archives/CQ2U3L6DC/p1582553063004200?thread_ts=1582548623.003200&cid=CQ2U3L6DC).
```
/private/var/tmp/_bazel_encalada/4bff13a28ce77172f0d977f092af385b/execroot/kubecf/bazel-out/darwin-fastbuild/bin/dev/cf_operator/apply.rb:23:in `<main>': undefined method `append' for #<Array:0x007fe96c854208> (NoMethodError)
```
Locally re-deployed kubecf; completed with no issues.
> fix: rules/helm: ruby < 2.5.0 compat

- README.md
Adds a link to https://kubecf.suse.dev/ in the README
> Add kubecf-docs to the links

- .concourse/pipeline.yaml
Instead of allowing forks, we just filter for PRs coming from branches of kubecf,
and we automatically trigger on those.
We can have automatic triggers for PR coming from branches, this ensures only who have write access to be able to use the CI
> Trigger concourse pipeline on kubecf branches

- dev/cf_operator/BUILD.bazel
- dev/kubecf/BUILD.bazel
- rules/helm/def.bzl
- rules/helm/upgrade.tmpl.rb
The bazel targets were using `helm upgrade --reuse-values` but that  reuses the values of the last deployment and applies the ones given on the command line. It discards changed
values in the chart itself.
What we actually want is `--reset-values` which resets the values to the
ones from the chart + command line.
This pr fixes a problem where changes to the `values.yaml` are not applied by running `bazel run //dev/kubecf:apply`.
Manual upgrades of a local deployment using the bazel target.
> Fix helm upgrades not applying changed values

- deploy/helm/kubecf/assets/operations/instance_groups/auctioneer.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
- Defines active-passive probes for the roles that need them
It is needed in order to have proper HA for all roles. The workaround up to know was to use a Readiness probe and let the "passive" pod in a not Ready state. With the probes in the PR, traffic is routed to pods using labels and selectors (created by the operator).
Closes #309 
Deployed kubecf with `high_availability: true` and Diego. Then checked the roles that got the probes to see if only one of the pods has the `active` label. The relevant services also got a selector. We checked that traffic is actually reaching only one of the pods by looking at their logs.
> Add probes for ha igs

- .concourse/pipeline.yaml
This adds a resource in the Concourse pipeline to allow triggering on PRs that come from forked repositories. We run all PRs from branches automatically but we need a way to manually trigger forked PRs.
> Add a trigger button for PRs based on forks

- deploy/helm/kubecf/assets/operations/buildpacks/set_suse_buildpacks.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/auctioneer.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/tcp-router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/kubecf/templates/_helpers.tpl
- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/brain-tests.yaml
- deploy/helm/kubecf/templates/database.yaml
- deploy/helm/kubecf/templates/eirini.yaml
- deploy/helm/kubecf/templates/ingress.yaml
- deploy/helm/kubecf/templates/ops-use-bits-service.yaml
- deploy/helm/kubecf/templates/ops.yaml
- deploy/helm/kubecf/templates/sizing.yaml
- deploy/helm/kubecf/templates/sync-integration-tests.yaml
- dev/linters/helmlint.sh
Using both `{{-` and `-}}` causes line breaks on both ends to be removed, sometimes resulting in unintended consequences.
e.g. 
[This code](https://github.com/cloudfoundry-incubator/kubecf/blob/63d9b24462f7e6a74ffe73ef625d46849e5761f4/deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml#L57-L60) results in the following render:
```
- type: replace
path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/quarks?
value:
ports:
- name: ssh-proxy
protocol: TCP
internal: 2222
run:
healthcheck:
ssh_proxy:
readiness:
httpGet:
port: 2223
path: /instance_groups/name=scheduler/env?/bosh/agent/settings/labels/app.kubernetes.io~1component
value: "ssh-proxy"
```
The array dash is no more, and the path and value keys override the ones from the previous element.
Fixes #414. …
> Remove template chunks that trim on both ends

- .concourse/pipeline.yaml
Also pin helm3 version in the pipeline
Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>
master branch no longer works with helm 2. This PR is adding CI support for helm 3.
> Bump catapult to support helm3

- deploy/helm/kubecf/assets/operations/releases.yaml
- deploy/helm/kubecf/templates/sizing.yaml
This makes [`sizing.yaml`] repeat itself less, like [`releases.yaml`].
[`sizing.yaml`]: https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/templates/sizing.yaml
[`releases.yaml`]: https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/assets/operations/releases.yaml
This makes sure we don't end up with a copy/paste error somewhere in _one_ sizing block: we move all the complicated logic on setting the sizes to one shared block, where we can focus our attention, and adding a new instance group is much simpler now.
As a side effect, also makes it possible to set size to 0 (since I'm now doing an explicit nil check).
Rendered the ops file manually (via `helm template`) to check that the output looks reasonable.  Checked HA mode (a much …
> fix: helm: reduce duplication in sizing ops

- deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
Fixes #451.
We don't want to use `--insecure` and `--skip-ssl-validation`. This PR fixes that by trusting the CA cert that the router cert was signed with.
The same behaviour for the security group setup was kept. CATS passed.
> fix: trust router CA cert on sec group setup

- deploy/helm/kubecf/templates/database.yaml
The seeder job was wrongly using the namespace for building the secret
names instead of the deployment name. That led to failing deployments
when those two were different.
Local deployment with different namespace and deployment name.
> Fix secret names used in the db seeder when ns != deployment name

- .concourse/pipeline.yaml
we introduced max-in-flight hoping to limit the number of clusters we
run at the same time. It turns out it doesn't work that way. As soon as
a deploy job is done the next one will be queued although no cluster has
been deleted. This will allow for as many clusters as we have time to
deploy until the first cluster is deleteted.
We also add the "version: every" setting to make sure we don't skip
versions if jobs complete in random order. See also here:
https://github.com/concourse/concourse/issues/736
Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>
> Remove max in flight and add every in the concourse pipeline

- deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
- deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
Fixes https://github.com/cloudfoundry-incubator/kubecf/issues/450.
If the admin password is changed, the credhub and uaa setups will fail.
Locally, checked that the security groups were created as expected not using the admin password.
> fix: use client credentials over admin password

- doc/database/manual-disaster-recovery.md
Fixes #438
Add example howto for pxc disaster recovery
If all database nodes in an HA setup fail at the same time the cluster is not always able to recover automatically. We need to a way to recover manually and have it documented.
In a development environment with kind where we terminated all three pxc nodes at the same time.
> Add example howto for pxc disaster recovery

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
This helps with concurrent test jobs, given that each job will be executed slower.
Generally, increasing concurrent test jobs decreases the total time spent running CATS, but also makes each individual test routines slower. Some of them times out and flake the tests.
Running CATS locally.
> feat: increase CATS scale timeout

- .concourse/pipeline.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
This PR intends to add [sync-integration-tests](https://github.com/SUSE/sync-integration-tests-release) to the [kubecf](https://concourse.suse.dev/teams/main/pipelines/kubecf) pipeline.
SITs form an important part of CF test suite.
fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/423
- Locally on catapult/kind.
- concourse.suse.dev CI.
> Adding SITs to kubecf concourse CI pipeline

- dev/cf_operator/.gitignore
- dev/cf_operator/BUILD.bazel
- dev/cf_operator/README.md
This makes the `cf-operator` deployment match that of the `kubecf` deployment, such that we can place `*values.yaml` files in `/dev/cf_operator` to customize the settings there.
We will also (by default) ignore all such files in git.
By default this has no effect (as there are no such files).
I wanted to be able to locally modify the cf-operator deployment.
Deployed locally.
> feat: cf_operator: allow values overrides

- rules/helm/def.bzl
- rules/helm/package.tmpl.rb
Using the branch name for automatic release versioning doesn't work well
with all CIs. It showed true for Concourse during release 1.0.0.
This new approach allows specifying a version of the packaging target.
If the version is not provided, the chart is versioned as it was before.
> fix: release versioning

- deploy/helm/kubecf/values.yaml
The pxc image lives in the cfcontainerization org like all the other images now.
> Use pxc image from the cfcontainerization org

- .concourse/pipeline.yaml
Added brain tests to the kubecf pipeline.
This is analogous to #436.
Note, this PR sits on top of that PR at the moment.
See ticket https://jira.suse.com/browse/CAP-1247
This is analogous to ticket https://jira.suse.com/browse/CAP-1280 for sits (and its PR).
This PR __requires__ the catapult PR https://github.com/SUSE/catapult/pull/117 (merged over the weekend)
Not tested. Unclear how to perform local testing of the changed pipeline.
> Added brain tests to kubecf pipeline

- deploy/helm/kubecf/templates/database.yaml
Fixes https://github.com/cloudfoundry-incubator/kubecf/issues/439.
Reference: https://github.com/cloudfoundry-incubator/cf-operator/pull/173.
Upon completion and success, the database-seeder job pod was left behind even after KubeCF helm installation was removed. This PR fixes this.
Deployed KubeCF and asserted that the QuarksJob controller deleted the pod upon completion.
> fix: auto-delete database-seeder pod

- deploy/bundle/BUILD.bazel
The cf-operator file in the bundle had the wrong naming pattern after
the refactoring of how the external files are handled. Now, the
cf-operator and KubeCF chart files in the bundle have predictable names.
The files in the bundle:
- cf-operator.tgz
- kubecf.tgz
Built the bundle and verified the cf-operator and kubecf charts with `helm inspect`.
> fix: cf-operator bundled with KubeCF

- .concourse/pipeline.yaml
The updates to `cleanup-eirini-cluster` were left behind. This PR fixes it.
This is a follow-up on https://github.com/cloudfoundry-incubator/kubecf/pull/497.
> fix: disable brain tests on CI

- .concourse/pipeline.yaml
- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
- Bump Catapult version to latest to include brain tests fixes https://github.com/SUSE/catapult/commit/543bc71abc8bd22e5ef81fdf94a7afeb2f99066d
- Fixes a leftover from the rotation test that hardcodes the deployment name, while there is a variable for it to consume
> CI: Bump catapult version to latest

- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
This is required for certain load balancers on public cloud to work correctly (e.g. ELB on EKS). See also https://github.com/SUSE/scf/pull/3179
Ciphers were selected based on recommendation from https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations
I've tested the change with both `sslscan` and directly via `openssl`, and see (some of) the new ciphers. Output from an alpha version of sslscan 2.0 (to use openssl 1.1 instead of 1.0.2 in the release version) shows:
```
Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits …
```
> Extend cipher suite for gorouter

- .concourse/README.md
- .concourse/fly
- .concourse/kubecf-pool-reconciler.yaml.gomplate
- .concourse/pipeline.yaml.gomplate
- .concourse/pool.yaml.gomplate
Fixes: https://github.com/cloudfoundry-incubator/kubecf/issues/501 . Introduce a pool mechanism to the KubeCF pipeline, and templates Eirini and Diego job definitions.
Kind clusters are now created by a separate pipeline, kubecf-pool-reconciler. This pipeline reconciles a "max pool size" by creating clusters and adding their kubeconfigs to the pool repository until the number of clusters in circulation match the "max pool size".
The KubeCF pipeline then consumes them, making jobs that have no resources to run, and wait for a lock that eventually will be created by the reconciler pipeline. The KubeCF pipeline will destroy the cluster and remove the kubeconfig from the pool when it finishes successfully, or in any job that has failed.
See: …
> CI: Use pool system for the pipeline

- deploy/helm/kubecf/assets/scripts/jobs/pxc/functions.sh
Use a sentinel file not touched by mysql itself and getting explicitly set when initialization has completed. This prevents slows systems from leaving a partial initialization behind where the old sentinel was already set, causing regular activation of the server on this and breaking.
See https://github.com/cloudfoundry-incubator/kubecf/issues/566
Stood up a cluster on the system where the issue occurred. Before the change the database pod gets stuck, never becomes running, and the remainder of the system is then stuck also.
With the change the cluster is standing up ok, the database pod takes longer to start completely, but start it does.
In a system where the issue does not (SSD backed) a cluster with the change also stands up ok, IOW the change is not breaking thing in general.
> Fix. Modified the database initialization sequence.

- .concourse/cap-release/README.md
- .concourse/cap-release/create_cap-release_pipeline.sh
- .concourse/cap-release/pipeline.template
- Implement pools and remove ekcp
CI now uses concourse pool resource. Inorder to test you cluster you will have to place you kubeconfig in ${backend}-kube-hosts branch of git@github.com:SUSE/cf-ci-pools.git in unclaimed folder.
- Fix triggers
This is a bug fix. Post deploy, CI's consequent jobs  were getting triggered by kubecf git resource. Now all jobs gets triggered via kubeconfig / pool resource
- Remove kubecf resource
kubecf github repo is not required in this CI as a resource.
- remove kubecf CI to avoid any confusion
Pool implementation  is required to manage locks on kubeconfigs while testing.
https://concourse.suse.dev/teams/main/pipelines/prabal-demo-release?group=eks
> CAP CI: implement pools

- .concourse/pipeline.yaml.gomplate
In this way the CI will run tests only if someone has approved it before, this could be also a gating mechanisms for forks, and we could also drop the special case for it. Discussed with @viovanov 
Sets `required_review_approvals` to 1 . It is enough 1 review to trigger CI runs, however the PR can be merged only if the required tests (prod) are successful. See https://github.com/telia-oss/github-pr-resource#source-configuration for more info about that option
In this way CI won't fire right immediately, and we can avoid to waste cycles for changes to the pipeline, or readme files for e.g.
N/A
> CI: Set required_review_approvals for PR resources

- .concourse/pipeline.yaml.gomplate
Also adds comment on prod and no-prod jobs and move disabled brains at the bottom
Fixes #593 #580 #597 and #455 
Move SITS and ccdb rotation jobs at the end of the pipeline. They haven't proved to be stable yet. Also it does the separation between "prod" and "no-prod" jobs and it just post the contexts of the prod jobs to Github (not all of them). 
I've added also the ability to post the status on Github for jobs in progress, so it covers #455, too.
They gate PRs CI runs even if they fails consistently
> Split KubeCF pipeline in prod and no-prod jobs

- deploy/helm/kubecf/assets/operations/instance_groups/adapter.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/log-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
Some YAML parsers won't like strings with colons without being quoted.
This commit fixes this by adding missing quotes.
> fix: add missing quotes when using [] syntax

- deploy/helm/kubecf/BUILD.bazel
- rules/kubecf/BUILD.bazel
- rules/kubecf/def.bzl
- rules/kubecf/release_chart.sh
This PR creates a helm-chart including the imagelist.txt based on @f0rmiga previous work.
We have added a new bazel target `//deploy/helm/kubecf:release_chart` which will unpack the helm chart created by `//deploy/helm/kubecf` and add the imagelist.txt containing all used images in the chart.
The imagelist helps us when creating tools consuming the helmchart and/or the contained images.
> Add imagelist to helmchart

- doc/tests.md
- doc/tests_brain.md
- doc/tests_cat.md
- doc/tests_sits.md
- doc/tests_smoke.md
- rules/kubecf/BUILD.bazel
- rules/kubecf/def.bzl
- rules/kubecf/test.tmpl.sh
- testing/BUILD.bazel
- testing/acceptance_tests/BUILD.bazel
- testing/acceptance_tests/trigger.yaml
- testing/brain_tests/BUILD.bazel
- testing/brain_tests/trigger.yaml
- testing/smoke_tests/BUILD.bazel
- testing/smoke_tests/trigger.yaml
- testing/sync_integration_tests/BUILD.bazel
- testing/sync_integration_tests/trigger.yaml
Each target triggers the test, waits for the pod to exist and then tails the test logs. The exit code of the script is the exit code of the test container.
There was no script to do the whole testing flow in the project.
Ran each of the tests under the `//testing` package. To list the targets:
```
bazel query //testing/...
```
To run each test:
```
bazel run <target>
```
> feat: improve testing targets

- def.bzl
Reverts cloudfoundry-incubator/kubecf#637
Reverting this cf-operator bump as the autoscaler-related services don't get created by cf-operator.
> Revert "Update cf-operator dependency."

- deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
Ops-files should be single YAML documents.
When --- is used, each YAML file is set to contain multiple documents,
which is undesirable when parsing many ops-files.
This is especially true for building the image list for KubeCF.
> fix: remove --- from routing-api ops-file

- .concourse/pipeline.yaml.gomplate
This makes catapult consume yq, yaml-patch, bazel, etc from the catapult CI
image run by concourse.
See: SUSE/catapult#162
Speeds up and simplifies CI runs.
The CI is already running on the refreshed catapult image built from https://concourse.suse.de/teams/main/pipelines/catapult.
Hijacked a build and checked that all new binaries are present and working on the image.
> Consume deps inside of docker catapult CI image

- BUILD.bazel
- def.bzl
- rules/external_binaries/def.bzl
The structure of the files exported by the repository_rule is simpler, allowing for easier dependency consumption from other repository rules.
Repository rules dislike symlinks for binary dependencies that we want to consume. E.g. passing the Helm binary to a repository rule requires the use of the real path, rather than the `:binary` target that returns a symlink to the real path.
With this change, the Helm binary can also be consumed via `@helm//:helm`, which happens to be the real path.
The `:binary` symlink is still useful for regular rules and should not be impacted by these changes.
Ran the `--help` for each of the binary dependencies we currently have using the `:binary` targets, as well as tried out the explicit binary location for helm and kubectl, which asserts that a `.tgz` and …
> fix: simplify the output of external_binary rule

- deploy/helm/kubecf/values.yaml
Bumps to latest bosh release to consume the loggregator-bridge including fixes for https://github.com/SUSE/eirini-loggregator-bridge/issues/4 
Couldn't reproduce https://github.com/cloudfoundry-incubator/kubecf/issues/576 anymore, see https://github.com/SUSE/eirini-loggregator-bridge/issues/6 see https://github.com/cloudfoundry-incubator/kubecf/issues/575  for the bump card.
Locally with kind
> Bump eirini-bosh release to 0.0.27

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/values.yaml
Fixes #625.
By default, the docker feature is disabled, making the docker suite on CATS to fail if not manually enabled.
The bump on the CATS release included in this PR handles this by enabling the docker feature while running CATS, then disabling it as part of the cleanup step.
Running CATS with the docker suite enabled by default and not having manually enabled the docker feature.
> feat: docker suite enabled by default on CATS

- README.md
- dev/kube/kube-ready-state-check.sh
Checking for Tiller is not needed anymore, we require helm >= 3.
Run `kube-ready-state-check.sh` by hand.
> Remove tiller check from dev/kube/kube-ready-state-check.sh

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
While investigating #524 I noticed that our ops-file to setup additional encryption keys does not keep the `cc_deployment_updater` job in sync. I didn't notice any effect of this, and it doesn't seem to be responsible for #524 either, which I couldn't reproduce even without this change in place.
I've also added a comment about the `cc_route_syncer` job, which is not part of cf-deployment, but used byCF-K8s-Networking. If we ever start using it, then it too will need to be updated with the encryption keys.
I have not looked how we are using `cc_deployment_updater` in kubecf (or if it is just a vestigial part from upstream that we don't use). I've not noticed any issues, but created this PR just for correctness sake.
I've tested this change locally with minikube.
> fix: Update database_encryption keys for cc_deployment_updater

- deploy/helm/kubecf/templates/eirini.yaml
- deploy/helm/kubecf/values.yaml
Fixes #595.
1. Added eirini cluster-role resources and verb properties under feature eirini. 
2. Add if condition in values.yaml, set customized resources and verb if eirini enabled and there are customized values for them. 
Since there is no way to extend the resources rules in https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/templates/eirini.yaml#L12 , unless you apply a manual change or a patch of the file. For some IaaS, the resources list requires more items, for example in IKS cluster, it needs this resource list: 
```
resources: ['mutatingwebhookconfigurations', 'nodes', 'nodes/proxy']
```
I did two tests, one is only to enable eirini feature, no properties under it. 
The other is to enable eirini feature, and added customized resources under it. …
> feat: user-provided ClusterRole rules for Eirini

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.yaml
- README.md
Directly triggers now on the PR, and Github resources cc @viovanov 
The concourse queue resource looses versions between jobs, some of them disappear :mage: 
Also fixes #669 , the publish step now is only attached to master, no need for checks anymore.
> fix: Remove queue mechanism from KubeCF pipeline

- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/ops.yaml
- deploy/helm/kubecf/values.yaml
Allowing users to provide inline operations via Helm helps with custom logic that needs to be applied on top of KubeCF. E.g.:
```yaml
operations:
inline:
- type: replace
path: /variables/-
value:
name: my_password
type: password
```
This reduces the number of manual steps to get a custom ops-file into KubeCF.
Improve the customization experience for the KubeCF user.
Locally, applying the above example. Then, verified that `var-my-password` gets created.
> feat: allow user to provide inline operations

- deploy/helm/kubecf/.gitignore
- rules/helm/BUILD.bazel
- rules/helm/def.bzl
- rules/helm/dependencies_charts.BUILD.bazel
- rules/helm/package.tmpl.rb
The dependencies repository rule is suited for fetching and caching Helm dependencies declared in the requirements.yaml file. Those dependencies are also known as sub-charts and are fetched as .tgz files under the charts/ directory. The rule exports a filegroup that selects all the charts to be used with the package rule.
This PR is to support the Eirini native Helm charts PR: https://github.com/cloudfoundry-incubator/kubecf/pull/651.
We want to include the Helm sub-charts in the final package, but still keep the fetching as part of a repository rule so it is aggressively cached to avoid network interaction during the build phase.
Added a few sub-charts to KubeCF and used the repository rule implemented in this PR:
```
load("//rules/helm:def.bzl", helm_dependencies = "dependencies") …
```
> feat: helm dependencies rules

- .concourse/pipeline.yaml.gomplate
- deploy/helm/kubecf/BUILD.bazel
Sets up KubeCF for v2.1.0 release.
There's still this manual step to release KubeCF.
Built the following targets locally:
//deploy/helm/kubecf:kubecf
//deploy/bundle:kubecf-bundle
//deploy/helm/kubecf:release_chart
Asserted that the chart for the correct version:
```
apiVersion: v1
appVersion: v2.1.0
description: A Helm chart for KubeCF
name: kubecf
version: v2.1.0
```
> feat: release v2.1.0 setup

- .concourse/pipeline.yaml.gomplate
Branch releases has dots in the names, which aren't supported by YAML anchors from `fly` :shrug: 
We can't deploy the pipeline for releases,  otherwise it fails with:
```
gomplate version 3.6.0, build 564f5588
config is:
input: pipeline.yaml.gomplate
output: -
rendered 1 template(s) with 0 error(s) in 597.951072ms
error: yaml: line 1716: did not find expected alphabetic or numeric character
```
With `fly` , now deployed on https://concourse.suse.dev/teams/main/pipelines/kubecf
> fix: sanitize branch names in the pipeline yaml anchors

- deploy/helm/kubecf/values.yaml
Bumps the brain test release to `v0.0.10`.
Ref: https://jira.suse.com/browse/CAP-526
Local invokation of the brain tests in a minikube based cluster.
__Note__: I have seen case `010` both passing and failing for the same commit, the bumped BTR version. Currently more suspecting glitchiness in my environment, hence why I decided to go forward with making a PR.
The failure hit the 10 minute limit. And according to the log I have the case actually succeeded. It just did not terminate. This seems to be what @mook-as has seen before in his local environment. More notes in the referenced ticket.
> Bump brain test release to v0.0.10.

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
This drops the app hostname prefix for the brains tests (`insecure-registry.tcp.*`) as that is not configured correctly for some deployments (e.g. kind).
Requires https://github.com/SUSE/brain-tests-release/pull/13
Required for https://github.com/SUSE/brain-tests-release/pull/13 to work correctly.
This is part of the fix for #29.
Running the changed test locally (minikube + `ClusterIP`).
> fix: brains: drop app prefix for insecure registry

- deploy/helm/kubecf/values.yaml
Trivially done by flipping the associated setting in the sub-chart configuration of kubecf.
Ref #796 
Tested locally in a minikube setup, SA. confirmed that the change removes the rootfsPatcher job and service account (vs present without the change). Smoke test has single identical failure regardless of change present or not. Not an issue of the change.
I suspect the security implications (less internet access from the system, so higher sec ?!)
Unclear if this is something we mention in the docs.
> fix: Disable the eirini rootfspatcher job.

- WORKSPACE
- deploy/helm/kubecf/BUILD.bazel
- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
- rules/helm/package.tmpl.rb
There was a workaround on the packaging rule that called `helm dep up` on every build.
This was wrong and the helm dependencies rule should be used.
Avoid network access during the build phase.
Built the chart locally using the correct rule and asserted the sub-charts are present in the final tarball.
> fix: use the helm dependencies rules

- deploy/helm/kubecf/values.yaml
KubeCf values.yaml is modified to point the eirini and bits sub-charts to SUSE-built images.
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] My code has security implications.
> Integration of SUSE eirini images into kubecf.

- doc/secret_rotation.md
- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
Update ccdb rotation qjob name in sample + doc
The qjob name is no longer prefixed with `kubecf` (or other helm release name)
> Update ccdb rotation qjob name in sample + doc

- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
Install eirini extensions as a subchart, so we don't need it separately.
Fixes #578 
* https://github.com/SUSE/eirinix-helm-release/pull/4
- so that we have a proper chart to use, instead of just using my development helm repository.
* #729
- otherwise loggregator-bridge is prone to crashing at startup
Deployed locally
> feat: eirini extensions as a subchart

- dev/build.sh
Ensures the build doesn't change files in the source tree.
> feat: check for changes in the tree after build

- deploy/helm/kubecf/templates/bosh_deployment.yaml
- deploy/helm/kubecf/templates/credentials.yaml
- deploy/helm/kubecf/templates/implicit_vars.yaml
- deploy/helm/kubecf/values.yaml
Credentials can be specified either with dot notation, or as a map:
```
credentials:
cf_admin_password: changeme
credhub_tls.ca: credhub-ca
credhub_tls.certificate: the-cert
credhub_tls.private_key: the-key
credhub_tls.is_ca: false
credhub_ca:
certificate: cert
is_ca: true
private_key: key
```
Variables are a simple list of key/value pairs:
```
variables:
system_domain: example.com
```
Note that setting the `system_domain` variable doesn't actually work because it is treated specially by the templates and has to be defined as `.Values.system_domain` instead.
See cloudfoundry-incubator/quarks-operator#895 for more details.
> feat: Implement credentials and variables settings in values.yaml

- deploy/helm/kubecf/values.yaml
In 8df8fd1d0a7cc8fd84ae3454af458340356285c3 we removed the eirini helm config value eirini.opi.logs.serviceName; this caused the eirini metrics pod to look for doppler-doppler instead (being the eirini chart's default value).  This caused the metrics to not be emitted correctly.
Fixes #803
Locally deployed with eirini, pushed an app, and checked that memory is reported as non-zero.
```
state     since                  cpu     memory        disk
#0   running   2020-05-07T21:28:58Z   99.8%   7.8M of 32M   40K of 100M
```
> fix: eirini not showing app metrics

- rules/kubecf/release_chart.sh
The tarball produced by `tar` is not in the format that `helm` expects it to be. Repackaging should be done by `helm` itself.
The `.tgz` file produced with the image list is not use-able directly without extraction.
Using `helm inspect chart`.
> fix: repackage using helm instead of tar

- dependencies.yaml
The minikube bump makes it easier to enable the metrics addon.
The kubernetes bump makes it possible to opt-in to ephemeral containers.
- I wanted to be able to install the metrics-server addon in minikube.
- I wanted to be able to use ephemeral containers to debug things.
Been running this locally for a few days, on a Linux host.
> feat: bump to minikube 1.9.2 / kubernetes 1.17.5

- .concourse/pipeline.yaml.gomplate
otherwise all parallel jobs will try to deploy a cluster with the same
name (the next version).
Deployed the pipeline
> Bump the gke cluster version before we even deploy

- dev/kind/start.sh
The `Corefile` for CoreDNS in the kind development environment is not
enabling the `ready` plugin when overriding the CoreDNS ConfigMap, but
it's relying on the :8181 endpoint for the readiness probe as of kubeadm 1.16.0
(6821d21260e3f7ad6eec0b0e5e8989187ac11794).
Then starting the `kind` environment, the `ConfigMap` of CoreDNS will be overriden but will not enable the `ready` plugin, so the `readinessProbe` will never succeed (introduced since kubeadm 1.16.0).
I created a `bazelisk run //dev/kind:start` environment. Before this change, `CoreDNS` pods will never reach a `Ready` state.
> kind development environment: enable `ready` plugin for CoreDNS

- .concourse/pipeline.yaml.gomplate
because we are now running on gke and we got CATs passing there in 23m
using 15 nodes.
> Increase CATs ginkgo nodes

- .concourse/pipeline.yaml.gomplate
Needed, since storageclasses and pvcs of the clusters have `reclaimPolicy:
Delete `, and the docs say that the disks corresponding to the pvcs default to
delete, but doesn't seem to be true. See:
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
https://cloud.google.com/sdk/gcloud/reference/compute/instances/set-disk-auto-delete
The gcloud account needs the following permissions:
- Required 'compute.disks.list' permission for 'projects/foo'
- Required 'compute.regions.list' permission for 'projects/foo'
Another implementation could be to label the cluster on creation and operate on
that.
Tested succesfully by hijacking a CI job, settings GKE_* vars manually, and using the commands to remove dangling disks of cluster kubecf-ci-0-0-27.
> Delete pvc disks associated with the GKE cluster in CI jobs

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
To import existing data from an SCF export, it must be possible to specify the encryption key label exactly, e.g.
```yaml
ccdb:
encryption:
rotation:
key_labels:
- NEW_KEY
current_key_label: NEW_KEY
credentials:
ccdb_key_label_new_key: abcdef
```
This means the label must be used verbatim, without the `ccdb_key_label_` prefix, and it must support uppercase characters.
Unfortunately this means that users upgrading kubecf from prior releases will have to manually add the hard-coded prefixes in their config file.
> fix: Use correct encryption key labels

- doc/release/release-guidelines.md
- doc/release/release.md
The `vX.Y.Z` format is used for tags and should be kept separate from the names for branches to avoid confusion once the branch and tag no longer point to the same commit.
The `release-X.Y` naming already matches the original intend, as show in the image used by `release.md`:
There is no separate release branch for patch releases; they all live on the release branch for their minor release (also as shown on the image).
> Release branch names are release-x.y and not vx.y.z

- .concourse/pipeline.yaml.gomplate
Project flag seems to be missing, see:
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego-master/builds/41#L5ebe73f8:2
Fixes cluster deletion task in CI.
It has not.
> fix: Add --project flag to gcloud compute disks delete

- .concourse/pipeline.yaml.gomplate
Disks can't be deleted if the cluster is still around. Save the list of disks to be deleted, delete the cluster, and then the disks.
No, difficult to test without triggering a job.
> fix: Permute the order of GKE cluster and disks deletion

- .concourse/pipeline.yaml.gomplate
Fixes the failure when trying to delete the "default-pool" disk, as it gets
deleted when we delete the cluster before.
No.
> Filter gcloud disks to list only pvc ones

- .concourse/pipeline.yaml.gomplate
Delete correctly the GKE clusters and their disks by filtering correctly for pvc disks.
Turns out that filters have an implicit `and`, but only between different types. Hence, bundle all name filters under a single  `--filter=name foo AND bar`. 
Tested by starting a deploy job on the kubecf pipeline, hijacking it, waiting for kubecf to be deployed so pvc disks are present, and then running the commands manually to completely delete the cluster and all its disks.
> fix: Delete correcly GKE disks, name filters need an explicit AND

- .concourse/kubecf-pool-reconciler.yaml.gomplate
- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
because there seems to be a performance penatly with overlay
baggageclaim driver in concourse and privileged containers.
https://github.com/concourse/concourse/issues/4332
With `privileged` on, it took 20 minutes to even start the `deploy` task. Without it it takes 10-20 seconds: https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/deploy-diego-master/builds/2
> Remove not needed "privileged" tasks from pipelines

- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
Bump the eirinix release to the version which has the resources prefixes removed.
See https://github.com/cloudfoundry-incubator/kubecf/issues/817
Manual in a minikube environment. Brought cluster up to the point where it was possible to confirm the removal of prefixes from the eirinix pods.
> Bump eirinix release to where the prefixes are removed.

- bosh/releases/pre_render_scripts/api/cc_uploader/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cc_uploader_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cloud_controller_api_ctl.sh
- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_file_server_ctl.sh
- bosh/releases/pre_render_scripts/asdatabase/postgres/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/auctioneer/auctioneer/jobs/patch_auctioneer_ctl.sh
- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_ctl.sh
- bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_json.sh
- bosh/releases/pre_render_scripts/diego-api/locket/jobs/patch_locket_ctl.sh
- bosh/releases/pre_render_scripts/diego-cell/cflinuxfs3-rootfs-setup/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_post-start.sh
- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_ctl.sh
- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_json.sh
- bosh/releases/pre_render_scripts/diego-cell/sle15-rootfs-setup/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/eirini/opi/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/router/gorouter/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/routing-api/routing-api/bpm/patch_bpm.sh
- bosh/releases/pre_render_scripts/scheduler/ssh_proxy/jobs/patch_ssh_proxy_ctl.sh
- bosh/releases/pre_render_scripts/singleton-blobstore/blobstore/jobs/patch_blobstore_pre-start.sh
- bosh/releases/pre_render_scripts/smoke-tests/smoke_tests/jobs/patch_test.sh
- bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
If the pod / containers go away unexpectedly (e.g. when a given node dies), we can get into a situation where the volumes holding the rendered job configs persist and things go bad for us:
1. Node goes away, the pod restarts (keeping volumes)
2. `cf-operator util template-render` re-renders the templates
(This clobbers our patched changes)
3. The patch script runs, seeing the sentinel file (because the volume
managed to survive), skipping the patching.
This fixes things by storing the digest of the _patched_ file in the sentinel, so that when this happens we see that the patch target has an unexpected checksum and we re-patch.
Fixes #852
Deployed locally. Murdered docker, see that issue does not recur.
> fix: ensure patches are applied

- deploy/helm/kubecf/values.yaml
Key labels are no longer automatically prefixed. We could extend the maximum length a bit to adjust for that, but 240 character seem long enough for just a label name.
Ref #853
> fix: outdated comment in values.yaml.

- deploy/helm/kubecf/BUILD.bazel
- rules/kubecf/release_chart.sh
This fix was applied after the `v2.2.0` tag, but used to build the `v2.2.0` release, but the `release-2.2` branch was based of the original tag.
> fix: Cherry pick packaging fix

- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
Otherwise the pods will not become ready until external DNS has been set up.
Fixes #870 
Tested manually by @satadruroy and @prabalsharma
> fix: Autoscaler should use internal URL for cloud controller

- .concourse/pipeline.yaml.gomplate
E.g. when cleanup failed, we didn't update the GH status
Deployed the pipeline. It's an edge case so a bit difficult to test it.
> Don't skip on_failure hooks when one of them fails

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
Various changes to improve the kubecf pipeline:
- Bump catapult to be able to use the GINKGO_EXTRA_FLAGS environment variable.
We need to set it to `-v --debug` to debug failures
Links:
- https://github.com/onsi/ginkgo/pull/499/files#diff-3baf47c64847a8fb8aaa8cc2e088513bR85
- https://github.com/SUSE/catapult/commit/c08b0244ab71bacb336873746a9df1f49005292f
- Set `trigger: true` in various jobs to let the pipeline flow when someone triggers a `deploy` job.
> Bump catapult

- deploy/helm/kubecf/values.yaml
Previous releases only allowed 16M for the smoke sample app, which turned out not to be enough for the SLE stemcell under Eirini.
See: https://github.com/cloudfoundry/cf-smoke-tests/pull/61
Fixes https://github.com/cloudfoundry-incubator/kubecf/issues/871
> Bump smoke-tests to increase app memory limit

- deploy/bundle/BUILD.bazel
- deploy/helm/kubecf/BUILD.bazel
- rules/helm/def.bzl
There was a fear that having it in the bundle was not visible enough; we will try moving it to the kubecf chart instead.
Fixes #916
Built the chart locally and inspected it for the sample values file.
> fix: deploy: move sample values into kubecf chart

- deploy/helm/kubecf/README.md
Adding README.md for general usefulness and to comply with Helm conventions. Linking to extant docs where possible. This is a very minimal list for the config section, and it needs to be expanded later.
> Add chart readme

- .concourse/pipeline.yaml.gomplate
to make sure they are not overwritten, ever.
Also enable the publish step in all branches except PRs. The publish
step removes the timestamp from the file and fails if the file already
exists.
Fixes #930
> Add timestamp (milliseconds) to the CI artifacts

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/values.yaml
It switches the default_stack from cflinuxfs3 to sle15.
Fixes #948.
https://github.com/cloudfoundry-incubator/kubecf/pull/945#issuecomment-635624549
specifies the expected functionality:
* `suse_buildpacks=false` and `suse_default_stack=false`
SUSE buildpacks are not installed, but the SUSE rootfs still is. We can discuss if the rootfs should be removed as well in the future, but in v2.2.x it has to stay for backwards compatibility.
However, buildpacks can be added back later via cf create-buildpack, but stacks cannot, so maybe both stacks should always be available.
* `suse_buildpacks=true` and `suse_default_stack=false` (current default)
SUSE buildpacks would be installed, but not used by default because the default stack remains cflinuxfs3.
* `suse_buildpacks=false` and …
> Add suse_default_stack feature flag

- deploy/helm/kubecf/values.yaml
automation broke it here: https://github.com/cloudfoundry-incubator/kubecf/commit/34bae8ae1
The java buildpack for sle15 stack is missing when you deploy. The reason is the wrong path to the buildpack file.
> Fix the path of the suse java buildpack

- rules/kubecf/image_list.tmpl.rb
The script already takes almost 10 minutes to run, and runtime will scale exponentially as more feature flags are added. Testing shows that all possible image names are detected by just expanding the templates twice: once with all features disabled, and once with all of them enabled.
Future changes are also expected to throw errors for certain feature combinations, which the current code also doesn't deal with.
> fix: image_list.rb only needs to check 2 feature combinations

- .concourse/pipeline.yaml.gomplate
to make sure the cleanup triggers when the pipeline is started by a
manual trigger of a job.
Concourse won't trigger jobs if an intput hasn't changed. When we retrigger a job we need to rely on a "new" version of some resource for the following jobs to start. We did that for other jobs but the cleanup was forgotten. This left clusters behind.
> Trigger the cleanup on the semver.gke_cluster resource

- deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/values.yaml
This PR uses #965 as the base, so that PR should be reviewed/merged first.
It switches the default_stack from cflinuxfs3 to sle15.
Fixes #948.
This is a new version of #960, which was merged without testing, and later reverted.
https://github.com/cloudfoundry-incubator/kubecf/pull/945#issuecomment-635624549 specifies the expected functionality:
* `suse_buildpacks=false` and `suse_default_stack=false`
SUSE buildpacks are not installed, but the SUSE rootfs still is. We can discuss if the rootfs should be removed as well in the future, but in v2.2.x it has to stay for backwards compatibility.
However, buildpacks can be added back later via cf create-buildpack, but stacks cannot, so maybe both stacks should always be available.
* `suse_buildpacks=true` and `suse_default_stack=false` (current …
> feat: Implement features.suse_default_stack.enabled

- .concourse/suse-buildpacks-ci/buildpack-version-bump/pipeline.yaml.gomplate
- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/pipeline.yaml.gomplate
This PR adds an exception for `filepath` of `suse-java-buildpack` while bumping its release image. Since [packaging](https://github.com/SUSE/cf-java-buildpack-release/blob/master/packages/java-buildpack-sle15/packaging) for java buildpack is different from others, we can't simply rely on filepaths from the buildpack package.
Also see: https://github.com/cloudfoundry-incubator/kubecf/pull/952
This creates a problem while bumping buildpacks and creates a commit like this https://github.com/cloudfoundry-incubator/kubecf/pull/851/files which is wrong.
https://concourse.suse.dev/
> CI: fix filename for suse-java-buildpack.

- dependencies.yaml
because linting now is broken in CI
Reason: https://github.com/koalaman/shellcheck/issues/1871
Urls from here: https://github.com/koalaman/shellcheck/releases/tag/v0.7.0
> Fix shellcheck binary urls

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
because the creation of a version is not an atomic operation and it
could happen that 2 deploy jobs use the same version. When one of them
fails it will trigger a deletion of the cluster although the other job
is still running. This results if failed jobs which are hard to explain.
Also add missing inputs in job
> Use a separate semver resource for each deploy job

- .concourse/pipeline.yaml.gomplate
Cleanup of clusters in the pipeline doesn't work:
```ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
- args: [u"ResponseError: code=404, message=Not found: projects/suse-225215/zones/europe-west3-c/clusters/kubecf-ci---0-0-5.\nNo cluster named 'kubecf-ci---0-0-5' in suse-225215."]
exit_code: 1
message: ResponseError: code=404, message=Not found: projects/suse-225215/zones/europe-west3-c/clusters/kubecf-ci---0-0-5.
No cluster named 'kubecf-ci---0-0-5' in suse-225215.
```
the reason is that we call the cleanup script but the needed vars "$BRANCH" and "$CFSCHEDULER" are not set. 
TODO
> Fix cleanup script by actually providing the needed env vars

- .concourse/pipeline.yaml.gomplate
because this together with `passed:` is confusing to Concourse and
doesn't let the step trigger when it should.
See also: https://github.com/concourse/concourse/issues/736#issuecomment-479557411
> Remove version: "every" from publish step artifacts

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
When a node is misbehaving in GKE it is sometimes removed or just changes Internal IP. We were using the internal IP with howdoi.website instead of a proper domain to run CATs. When the node IP changes our DOMAIN is no longer valid and tests fail.
This happens quite often leading in a lot of flakiness in the pipeline.
This PR is setting up a subdomain of `kubecf.ci` for each testing cluster and points that to the given public IP of the router service. It cleans up the dns records in the end.
Deployed a copy of the pipeline, let it run and checked if cleanup happened in the end.
> Setup proper dns on gke

- .concourse/pipeline.yaml.gomplate
This PR makes sure we delete not used disks that were created dynamically for PVCs. The reason is that when preemptible nodes are used the disk don't get deleted automatically (https://cloud.google.com/compute/docs/instances/preemptible#understanding_the_preemption_process). There is one more disk for the master node but that one gets deleted automatically (checked).
Another solution would be to not use preemptible nodes.
Disks are left behind and they cost money. Also at some point we hit the disk quota (because we don't cleanup).
Tested the commands locally.
> Delete all unused disks

- deploy/helm/kubecf/templates/NOTES.txt
Add a helm `templates/NOTES.txt` which gets shown on `helm install`.
The NOTES.txt points to https://kubecf.suse.dev/docs for documentation, which seems like a good starting point.
Closes https://github.com/cloudfoundry-incubator/kubecf/issues/855.
Successfully tested by deploying the resulting chart and checking that the NOTES.txt are displayed correctly.
> feat: Add NOTES.txt to helm chart

- bosh/releases/pre_render_scripts/diego-api/cfdot/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-api/cfdot/jobs/patch_setup.sh
- bosh/releases/pre_render_scripts/diego-cell/cfdot/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/cfdot/jobs/patch_setup.sh
- bosh/releases/pre_render_scripts/scheduler/cfdot/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/scheduler/cfdot/jobs/patch_setup.sh
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
Patched cfdot job prestart to a shared location accessible in all the container of an instance group. The patches are all the same for the three affected instance groups. (As the job itself is the same).
Added comments to the diego-cell patch setup as a reminder to maintainers as to the intent of the complexity.
See ticket #738 
Testing was done in a local minikube deployment. After the cluster became :heavy_check_mark: all affected instance groups were entered into via `kubectl exec`, the `cfdot.sh` was sourced from its new location and then a few `cfdot` commands invoked (`--help`, `locks`, `task`, `domains`, `cells`, `presences`.).
> Make cfdot available in a properly shared location.

- .concourse/README.md
- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
Setting `github_status: false` disables publishing github status, which is
desired when deploying a test or development pipeline.
Needed for deploying copies of the pipeline.
Rendered the kubecf pipeline against the production one with `./create-pipeline.sh`, with both `github_status: false` and `true`. Saw expected changes on the former, and no changes on the latter.
Given that `github_status: false` removes the resource, I'm confident that there aren't any leftovers when setting it, as Concourse would refuse to fly it.
> feat: Add github_status option and template pipeline to use it

- bosh/releases/pre_render_scripts/asactors/operator/jobs/patch_operator_ctl.sh
- bosh/releases/pre_render_scripts/asactors/scalingengine/jobs/patch_scalingengine_ctl.sh
- deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
- dev/kube/klog.sh
Added autoscaler patches to render `pid_guard` in scalingengine and operator inert.
Prevents a platform from failing to properly restart these jobs at container level after a transient failure (uaa connectivity, for example) due to the new pid for the control/main process being the same as in the failed container, and thus aborting the restart in the mistaken belief of the previous process still running (while actually looking at the new process).
A side change is an extension of the `klog.sh` tool with a new option `-r` to retrieve not just logs from a CF cluster, but also the rendered scripts and configuration files.
See #928 
Manually via catapult, see ticket comment https://github.com/cloudfoundry-incubator/kubecf/issues/928#issuecomment-634309394 Main difference from the reproduction …
> Fix CLBO in autoscaler after transient failure to connect to UAA

- deploy/helm/kubecf/charts/bits/Chart.yaml
- deploy/helm/kubecf/charts/bits/templates/bits.yaml
- deploy/helm/kubecf/charts/bits/values.yaml
- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
- deploy/helm/kubecf/values.yaml
Subordinate PR at SUSE/bits-service-release#6
This PR sets the defaults to nil to disable resource requests.
Also bumped to the new bits release containing the ability to configure the resource requests. Version 1.0.17.
See #861.
Tested locally in a minikube that changes to the defaults in the kubecf values.yaml are properly propagated into the bits pod.
> Clear resource requests from eirini bits service.

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
- .concourse/tasks/upgrade.yaml
Fixes to upgrade script and pipeline spec driving it.
- Script:
- Placed kubeconfig at an accessible location.
- Replaced concourse and gomplate templating with environment variables controlled by proper task parameters.
- Added checks for parameter existence.
- Fixed catapult backend, must be `gke`, not `imported`.
- Fixed yaml indenting in the disk override.
- Added comments explaining internals, and the various communication
variables (gcloud, catapult).
- Pipeline:
- Fixed scoping of `kubecf_repository` usage in loop.
- Added parameters for the upgrade task.
See https://github.com/cloudfoundry-incubator/kubecf/issues/838
Manual testing using a non-production pipeline.
Pointed at the personal fork for the kubecf repository to use.
See …
>  Fix upgrade testing in the kubecf CI pipeline

- .concourse/pipeline.yaml.gomplate
In some cases the internetless suite doesn't trigger although previous step is green. That leads to dangling clustets (since not job failed to trigger a cleanup).
Deployed the pipeline and hoped for the best. Time will tell.
> Make internetless suite not public and fix triggering

- .concourse/tasks/upgrade.sh
Remove unneeded vars in the upgrade pipeline task, use defaults already present.
Set Catapult vars to not download and install gcloud inline and provide plaintext input.
Perform `cf login` after `helm install` and afer `helm upgrade`, as sanity check.
Speeds up the test because gcloud cli is not downloaded and installed, makes clearer what is happening.
Not tested. Because of line https://github.com/cloudfoundry-incubator/kubecf/blob/viccuad-upgrade-clobber/.concourse/pipeline.yaml.gomplate#L1401, one needs to deploy a pipeline that targets this `viccuad-upgrade-clobber` branch, and that is blocked by https://github.com/cloudfoundry-incubator/kubecf/issues/1032.
> Remove unneeded vars in the upgrade task of the kubecf pipeline

- .concourse/tasks/upgrade.sh
Login only after setting DNS, instead of before, which surely fails.
Not tested. Because of line https://github.com/cloudfoundry-incubator/kubecf/blob/viccuad-upgrade-clobber/.concourse/pipeline.yaml.gomplate#L1401, one needs to deploy a pipeline that targets this viccuad-upgrade-clobber branch, and that is blocked by #1032.
> Login only after setting DNS

- .concourse/tasks/upgrade.sh
Don't do kubecf-login in upgrade task.
Update the GKE code in the upgrade job to match the rest of the pipeline.
Not tested. Because of line https://github.com/cloudfoundry-incubator/kubecf/blob/viccuad-upgrade-clobber/.concourse/pipeline.yaml.gomplate#L1401, one needs to deploy a pipeline that targets this viccuad-upgrade-clobber branch, and that is blocked by #1032.
> Pipeline: Remove kubecf-login from upgrade task.

- .concourse/tasks/upgrade.sh
Added back double quotes variables in:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/.concourse/tasks/upgrade.sh
Removing the double quotes fails lint stage in pipelines:
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/lint-master/builds/4
Implementing fix to pipeline and running against local concourse
Before:
After:
> Fix for failing update-test during lint stage

- deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
- deploy/helm/kubecf/values.yaml
When you delete a job with `kubectl` the created pods get deleted too. But when quarks-job deletes a job it doesn't delete the pod unless the `delete: pod` label is set on the job.
See also:
- https://github.com/cloudfoundry-incubator/quarks-job/blob/master/docs/quarksjob.md#job-controller
- https://github.com/cloudfoundry-incubator/quarks-job/blob/b16b2a026f867b8e4c8acc070735864dc5c3f6d8/pkg/kube/controllers/quarksjob/job_reconciler.go#L96
For the kubecf pipeline, we will cleanup the pod manually in catapult because we need the pod to be around for a while to be able to write the logs on a file. If quarks job deletes it, then we may not get the chance to do that (https://github.com/SUSE/catapult/pull/232).
I opened this PR in case it is useful for some other pipeline or use case. I know …
> Cleanup pods after tests

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
When a branch is called `2.2` the pipeline fails with errors like:
```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Invalid value for field "cluster.name": "kubecf-ci-release-2.2-diego-0-0-2". Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)' (only alphanumerics and '-' allowed, must start with a letter and end with an alphanumeric, and must be no longer than 40 characters).
```
> Replace dots with dashes in cluster names because GKE doesn't like dots

- .concourse/tasks/upgrade.sh
Don't call kubecf-login on upgrade.sh. It will never work, DNS is set as private, only accessible from inside the cluster.
Deployed https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad, and named the git branch with a short enough name so GKE clusters can start.
> Don't call kubecf-login on upgrade.sh

- deploy/helm/kubecf/BUILD.bazel
Bump kubecf chart version to v2.3.0
Needed, as explained in https://github.com/cloudfoundry-incubator/kubecf/blob/release-2.2/doc/release/release-guidelines.md#files-to-change.
To be run by the pipeline. We should see the build job in the PR create a `kubecf-2.3.0-hash` artifact, instead of a `kubecf-0.0.0-hash`.
> Bump kubecf chart version to v2.3.0

- .concourse/pipeline.yaml.gomplate
Move green jobs to the production tab. A full CI run seems will take ~2 1/2 hours.
Once this is merged, the GH status check for them need to be [enabled](https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks).
To gate PRs by the green jobs and not introduce regressions.
Deployed https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad
That pipeline is deployed with the changes on the `viccuad-mv-prod-jobs`, plus _also_ tracking this branch:
```patch
-{{ $branches := slice "master" "release-2.2" "release-2.3"}} # Repository branches to track
+{{ $branches := slice "viccuad-mv-prod-jobs" }} # Repository branches to track
```
Currently, jobs and pipeline are paused. To test this PR:
1. Approve PR. this will put it in the queue
2. Pin this PR …
> CI: Move green jobs to the production tab

- deploy/helm/kubecf/assets/operations/azs.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
- deploy/helm/kubecf/templates/database.yaml
- deploy/helm/kubecf/values.yaml
App Autoscaler released a new version 3.0.1 https://bosh.io/releases/github.com/cloudfoundry-incubator/app-autoscaler-release?all=1. This new release can use both Postgres and MySQL as database.  
This changes changes to the new version 3.0.1 and can choose embedded_database of cf deployment as database.
To support the new Autoscaler 3.0.1 release.
Test manually in the minikube. 
cf-operator:v4.5.6-0.gffc6f942
- [] My code has security implications.
> update autoscaler to 3.0.1 and add mysql support 

- bosh/releases/pre_render_scripts/routing-api/routing-api/bpm/patch_bpm.sh
Just added comments to the patch script explaining why we cannot upstream.
See #521 for the discussion.
No testing was done, pure comment changes.
> Add comment on why we cannot upstream the routing-api bpm patch

- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
move variables from pipeline definition to config file - https://github.com/cloudfoundry-incubator/kubecf/issues/1084
- Moved variables from pipeline definition to config file: kubecf.yaml
- Renamed `stable ` and `experimental` to `stable_jobs` and `experimental_jobs`, respectively 
https://concourse.suse.dev/teams/main/pipelines/prabal-kubecf?group=pr
When kubecf CI will be updated with this kubecf.yaml, there will be `no changes to apply` to the CI.
> move variables from pipeline definition to config file

- .concourse/pipeline.yaml.gomplate
Add GH status reporting to upgrade when it is on stable jobs.
Reporting copied from smoke-tests after rotation:
- pending
- success
- failure (on abort, on error, on pipeline failure)
To gate PRs with the upgrade job.
Deployed pipeline with this changes here: https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad/jobs/upgrade-test-master
> CI: Add GH status reporting to upgrade when it is on stable jobs

- .concourse/pipeline.yaml.gomplate
Update the pinned catapult version to support using quarks-operator 5.x.
We're having issues landing #1049 because the catapult we have doesn't support quarks-operator 5.x, and we don't want to land that until CI passes (because that's always bad).
Used the relevant catapult locally.
> fix: concourse: update catapult for operator 5.x

- .concourse/pipeline.yaml.gomplate
https://github.com/cloudfoundry-incubator/kubecf/issues/1092
pipeline can be deployed with github_status set to false
> fix pipeline for github_status set to false

- .concourse/tasks/upgrade.sh
This backports a fix from master for the upgrade task in CI.
Testing for `cf login` will never work, `make kubecf-login` tries to `cf login` outside of the cluster,
and the DNS is set as private.
We saw the same behaviour on master CI.
> CI: Don't try to `cf login` in .concourse/tasks/upgrade.sh

- .concourse/README.md
- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
Add pr_base_branch option to filter PRs by which branch(es) they target.
The resource either allows for the parameter to be set to 1 branch, or not set,
for all branches.
See: https://github.com/telia-oss/github-pr-resource#source-configuration
Needed for https://github.com/cloudfoundry-incubator/kubecf/issues/1095.
Manually set the new option `pr_base_branch` to `~`, `release-2.3`, `foo` and verified the gomplate works as intended. Deployed kubecf-viccuad pipeline with those options and verified that the kubecf-pr resource lists the correct PRs to test.
> CI: Add pr_base_branch option to filter PRs by which branch(es) they target

- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
Add `workertags` option to pipeline config.
It can be null for no tags, or an array of tags.
Allows to deploy and run the pipeline only in some specific concourse worker.
https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad
> Add `workertags` option to pipeline config

- .concourse/README.md
- .concourse/kubecf-release-2.3.yaml
- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
This PRs backports as less code as possible and allows to deploy a pipeline for `release-2.3` branch:
- Backport:
- move pipeline vars to config file
- add github_status for upgrade
- fix rotate_credentials job by adding a wait afterwards
-  add `pr_base_branch` pipeline option
- Create new `./concourse/kubecf-release2.3.yaml` configuration file with sane options, for the new `kubecf-release-2.3` pipeline.
Implements https://github.com/cloudfoundry-incubator/kubecf/issues/1095 for `release-2.3` branch.
Decided to cherry-pick individual commits (`git cherry-pick -x <sha>`, fix minimal conflicts), and not merge commits.
Deployed pipeline https://concourse.suse.dev/teams/main/pipelines/kubecf-release-2.3. Note that the pipeline is production ready and should stay, and the PR tab tests only …
> Backport needed CI code to release-2.3 branch

- .concourse/kubecf.yaml
- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
- .concourse/tasks/upgrade.yaml
Ensure cluster resources between pipelines don't collide:
* Namespace gke cluster names with the pipeline name
For this, add new pipeline option `resource_prefix: kubecf`
This option prefixes the cluster names, and allows to deploy copies of the
pipeline for development.
* Remove `kubecf-ci` from GKE cluster names, or they get truncated
GKE cluster names get truncated at around ~14 chars. We use them as a poor-man
substitute for atomic pools. Remove `kubecf-ci` prefix on the GKE cluster names,
so clusters like `kubecf-ci-kubecfmaster`, `kubecf-ci-release-2.3`,
`kubecf-ci-release-2.2` don't get truncated to `kubecf-ci-rele`, losing the
atomicity.
Closes https://github.com/cloudfoundry-incubator/kubecf/issues/1095 (be able to deploy pipelines from the branch code, not from master).
This …
> CI: Ensure cluster resources between pipelines don't collide

- .concourse/kubecf-release-2.3.yaml
Update release-2.3 pipeline config to consume new options. After fast-forwarding, there are new options to set in the pipeline config, and the pipeline needs to be reflown.
Fails to deploy clusters if not, because we name the clusters to make them unique per branch and copy of the pipeline.
Redeployed release-2.3 pipeline, upgrade job is working now: https://concourse.suse.dev/teams/main/pipelines/kubecf-release-2.3/jobs/upgrade-test-release-2.3/builds/4
The other deploy jobs work the same, but I haven't triggered them; they will get triggered automatically when there's a new commit, such as this PR.
> CI: Update release-2.3 pipeline config to consume new options

- scripts/kubecf-apply.sh
`xip.io` is often flaky, so make it easy to switch to an alternative.
> Make xip.io domain configurable for dev setups

- deploy/helm/kubecf/values.yaml
This pulls in fixes for skipping tests.
Attempting to run brain tests with some test skipped just fails instead.  Also has a fix for storage class annotations (for AKS).
Pulls in https://github.com/SUSE/brain-tests-release/pull/17.
Ran brain tests locally.
> feat: helm: update brain-tests release to v0.0.13

- .concourse/pipeline.yaml.gomplate
- doc/release/release-guidelines.md
- rules/helm/package.tmpl.rb
- scripts/version.sh
Remove `v` char from the semver string, to be fully compliant with semver, both in bazel and shell based build systems.
This changes the resulting artifact name from the build; adjust regexps and shell expansion in pipeline
to consume them. 
If merged, this would surely trigger changes downstream for consuming the tars and version string.
Another implementation could be to not change the artifact name, and only the yaml value in `Chart.yaml`. This seems hackish, and given that the call to building with helm is `helm package  --version "${VERSION}" …`, seems foolish.
Closes https://github.com/cloudfoundry-incubator/kubecf/issues/927.
Deployed pipeline from this branch at https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad?group=viccuad-semver-full.
Tested also by rebasing this …
> Remove `v` from kubecf's version string, and consume correctly

- Makefile
- scripts/cf-operator-wait.sh
- scripts/kubecf-wait.sh
- scripts/tools/retry.sh
This adds two new targets for the make-based build system, which can be used to wait for cf-operator & kubecf to finish deploying.  This is useful in CI where we may want to let things settle before running the consequent steps (e.g. to run tests).
Wanted to use this in CI (spiking on using GitHub actions, but this is useful elsewhere).
Ran a lot.
This change is for development only, this has no effect on the shipped code.  It is also currently not used anywhere.
> feat: Add wait targets for make

- Makefile
- scripts/tools/retry.sh
* Don't display errors from the command checking status; it is expected to fail while the status is not yet ready.
* Display time since the start of the script for each wait check, in addition to the retry/max counts.
* Overwrite status output for a single check when writing to a tty to avoid massive scrolling.
Also add an `all` target to deploy cf-operator and kubecf, and then log in when everything is ready, e.g. `FEATURE_EIRINI=1 make all` to run kubecf with Eirini on the cluster specified by the current `KUBECONFIG`.
> feat: Improve wait scripts for interactive usage

- .concourse/pipeline.yaml.gomplate
This should clone submodules and fix PR testing.
The get step uses the resource `kubecf-{{ $branch }}`, and depending on the
range, it will either be:
- kubecf-{master, release-2.3, etc}, which is the git resource
- kubecf-pr, which is the SUSE/github-pr-resource
Each has a different behaviour for the `submodules` param, the former defaults
to all, the later accepts a boolean and defaults to false. Hence, the `if`.
Fix flown already, https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/lint-pr/builds/110 doesn't fail because of submodule not initialized, as https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/lint-pr/builds/109 used to do.
> Add params.submodules true if using the pr resource on kubecf-pr

- dev/minikube/def.bzl
- scripts/minikube-start.sh
Kube 1.18 needs conntrack, which was missing from the older image. Leaving default K8S_VERSION=1.17.5 because most public clouds still use that (and because metadata.managedFields is really annoying when looking at pods).
> Bump minikube iso image to 0.1.8 supporting k8s 1.18

- Makefile
- scripts/README.md
- scripts/kubecf-apply.sh
- scripts/kubecf-build.sh
It got broken in cac7e60; all scripts are missing the .sh file extension.
> Fix 'all' Makefile target

- scripts/minikube-start.sh
It had a mismatched version (0.1.6 vs 0.1.8) which means it couldn't be downloaded at all.
Trying to start minikube failed.
Started minikube on a machine that previously failed.
> fix: scripts: Fix minikube ISO download URL

- deploy/helm/kubecf/generate-minions-values.sh
Provide a new script which will looks at the control plane  and generate a values yaml to help with configuring a worker cluster.
While building a multi-cluster kubecf, configuring a cluster worker requires many informations and credentials from the control plane cluster. It's hard to find all the required values and put them in worker clusters values file manually. 
This script can do that job automatically.
fixes https://github.com/cloudfoundry-incubator/kubecf/issues/939
testing environment:
The control plane of multi-cluster kubecf
test 1) run with kubectl configured connecting to a control plane of multi-cluster kubecf, specify the options -o and -t
```
$ bash generate-minions-values.sh -o test-minions-values.yaml -t test
Generating value file for minions cluster ...
add …
```
> Script to generate a values.yaml for worker clusters

- doc/architecture/decisions/0002-git-commit-messages.md
Switch the breaking change definition from a the word "break" to the exclamation mark "!".
To follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specifications.
N/A
N/A
N/A
N/A
> docs: replace breaking change commit definition

- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
Refactor rotate-ccdb-keys-test.sh to remove Bazel dependency.
Needed by https://github.com/cloudfoundry-incubator/kubecf/issues/1010
Tested successfully, the change on the rotate job in the following pipeline succeeds:
https://concourse.suse.dev/teams/main/pipelines/kubecf-rmbazel/jobs/ccdb-rotate-diego-viccuad-rm-bazel-rotate
> Refactor rotate-ccdb-keys-test.sh to remove Bazel dependency

- .concourse/pipeline.yaml.gomplate
This is required for the new kubecf-tools/versioning code to work.
> Bump github-pr-resource image to pull down tags

- .gitmodules
- scripts/include/versions.sh
- scripts/version.sh
Adds kubecf-tools repo as a submodule per discussion with @viovanov 
The new versioning script was developed via #1013
Fixes #766
Example output:
```
$ make version
0.2.0-1455.gfa0a32f0-dirty
```
Requesting review from @viccuad to make sure it is compatible with catapult and CI.
> Use new versioning script from kubecf-tools

- doc/dev/general.md
Like mentioned in https://github.com/cloudfoundry-incubator/kubecf/pull/1097
it was missing the correct service names as with https://github.com/cloudfoundry-incubator/kubecf-docs/commit/8d8c10d12a0c7c120846e038030cce0b21bb5526
Fix https://github.com/cloudfoundry-incubator/kubecf/commit/ee6b8bd6d648106cd2296c68bdffd6f1e58d72bc according to https://github.com/cloudfoundry-incubator/kubecf-docs/commit/8d8c10d12a0c7c120846e038030cce0b21bb5526
Deployed kubecf with nginx-ingress
> Fix docs commit to be in line with kubecf-docs

- deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
- deploy/helm/kubecf/charts/bits/Chart.yaml
- deploy/helm/kubecf/charts/bits/templates/bits-config.yaml
- deploy/helm/kubecf/charts/bits/templates/bits.yaml
- deploy/helm/kubecf/charts/bits/values.yaml
- deploy/helm/kubecf/charts/eirini-extensions/templates/ssh-proxy.yaml
- deploy/helm/kubecf/charts/eirini-extensions/values.yaml
- deploy/helm/kubecf/charts/eirini/Chart.yaml
- deploy/helm/kubecf/charts/eirini/templates/configmap.yaml
- deploy/helm/kubecf/charts/eirini/values.yaml
- deploy/helm/kubecf/requirements.lock
- deploy/helm/kubecf/requirements.yaml
- deploy/helm/kubecf/templates/eirini.yaml
- deploy/helm/kubecf/values.yaml
This drops hard-coded instances where we assumed the Kubernetes cluster domain to be `cluster.local`; doing this is required as this isn't guaranteed on all Kubernetes deployments.
Fixes #872 
Deployed locally (using Eirini), with a custom minikube:
- `MINIKUBE_EXTRA_OPTIONS` includes `--dns-domain=minikube --extra-config=kubelet.cluster-domain=minikube`
- Quarks-operator helm config includes `cluster.domain=minikube`
- Double checked that `/etc/resolv.conf` in the CC container doesn't include `cluster.local`
⚠️ Need to see how #1119 interferes with this PR.
> Eirini: drop cluster.local references

- scripts/test.sh
No longer assume that there is only one pod for running the test; instead, take a snapshot of the pods before patching the qjob, and find the new one instead.  This is necessary to re-run a (succeeded) test, as the pods are not deleted automatically after a test passes.
I tried to run `make smoke` a few times in a row (to test updating across different configs), only the first run works correctly.  For the other runs, it tries to find a pod where the name contains `\n` (because it's actually multiple pods).
Ran `make smoke` a few times.
> fix: scripts: Deal with re-running tests better

- scripts/cf-operator-apply.sh
- scripts/include/versions.sh
- scripts/kubecf-build.sh
- scripts/kubecf-bundle.sh
- scripts/tools/cf_operator_url.sh
That is the only location updated by CI when we bump the cf-operator version, so this commit makes sure we don't get out-of-sync between bash and bazel build rules.
> Read cf-operator URL and SHA256 from dependencies.yaml

- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
Use containerd as default container manager in diego-cell
KubeCF Diego is using RunC as the default contaienr manager, but Containerd is the default container manager in cf-deployment: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1544,  this change is to set containerd as default container manager in diego-cell.
Containerd is the default container manager in cf-deployment, that means containerd is used widely and was tested well, so KubeCF should use containerd as the default container manager.
Smoke Testsuites passed.
The Diego Cell is using containerd as below:
```
/:/var/vcap/jobs/garden# /var/vcap/packages/containerd/bin/ctr -a /var/vcap/sys/run/containerd/containerd.sock -n garden tasks ls
TASK                            PID     STATUS …
```
> Use containerd as default container manager in diego-cell

- bosh/releases/pre_render_scripts/diego-cell/garden-cni/jobs/patch_pre-start.sh
- bosh/releases/pre_render_scripts/diego-cell/silk-cni/jobs/patch_pre-start.sh
- deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
- deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
enable silk in diego
Diego in KubeCF is still using a Garden network implementation which is not maintained actively by the community, the default container network in Diego is silk. This change is to enable silk in KubeCF.
Silk is the default container network implementation in Diego, and it's more reliable than Garden network implementation, and is maintained actively by the community.
Smoke testsuite passed 
```
Running smoke tests...                                                                                                                                                                                                                     │
│ Running binaries smoke/isolation_segments/isolation_segments.test …
```
> enable silk in diego

- scripts/include/tools.sh
Have a cache of tool status, so that require_tools will not repeatedly try to determine if the same tool has been installed.  This also lets us catch when a tool (possibly through others) end up requiring itself.
It is slow when building things.
Before the change:
```
$ { for i in $( seq 1 3 ) ; do time make kubecf-build  ; done ; } 2>&1 | grep real
real    0m29.602s
real    0m29.171s
real    0m29.155s
```
After the change:
```
$ { for i in $( seq 1 3 ) ; do time make kubecf-build  ; done ; } 2>&1 | grep real
real    0m23.592s
real    0m23.637s
real    0m23.230s
```
> fix: scripts/include/tools.sh: cache tool states.

- scripts/cf-operator-apply.sh
This adds an override to `cf-operator-apply.sh` to be able to pass in custom helm values.
I'm happy to entertain bike shedding of the variable name.
This is useful when trying to deploy custom overrides to the operator (e.g. to use a custom docker image).  This is not used by default.
Deployed locally with a custom operator helm values file (so that I could develop the operator locally and test it against kubecf).
> feat: cf-operator-apply: accept extra values

- deploy/helm/kubecf/assets/operations/sizing.yaml
- deploy/helm/kubecf/templates/database.yaml
- deploy/helm/kubecf/values.yaml
Default rules are added to all instance groups, including pxc/database, but not to bits/eirini/eirini-extension subcharts.
All instance groups have anti-affinity against themselves, and diego-cell and router additionally against each other.
fixes #254 
fixes #606 
This commit is expected to be cherry-picked into the release-2.2 branch.
This PR has been tested locally, by deploying twice on minikube: first with no custom settings, and then with these overrides:
```
sizing:
api:
affinity:
podAntiAffinity:
preferredDuringSchedulingIgnoredDuringExecution:
- weight: 100
podAffinityTerm:
labelSelector:
matchExpressions:
- key: quarks.cloudfoundry.org/quarks-statefulset-name
operator: In
values:
- sample_group
topologyKey: kubernetes.io/hostname
database:
affinity:
podAntiAffinity: …
```
> Add default podAntiAffinity rules and sizing.*.affinity overrides

- scripts/include/tools.sh
If a tool has no requirements, we can end up in a situation where we try to expand something approximating `${TOOL_STATUS[""]}` because we had a loop for `for tool in ""`; bash throws a fit at this nonsense.  Sanity check for that case, so we don't fall over.
I had local tools that triggered the error condition.
Ran the relevant local tools.
> fix: scripts/tools: skip empty tools on require

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
To support the early identification through filters when a new issue is opened and to avoid orphans issues for too long.
I need to be constantly searching for "no:project" issues and this can't be applied to Github filters.
Will check by opening a new issue .
> feat: add validation label so it can be easily identified before moved to a project

- bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_set_kernel.sh
- chart/assets/operations/instance_groups/diego-cell.yaml
- Removed the deployment patch instruction disabling the setting of
KPs by `rep` -> The prestart script invokes code setting the KPs.
- Added a patch modifying the `rep` prestart script. Added removal
of ubuntu specific code from the code path setting KPs.
- Modified the `rep` runtime setup. Made the container privileged.
The SYS_ADMIN capability used to allow AppArmor was not enough to
allow setting of KPs.
See ticket #1181 
Used a local minikube to deploy the modified chart (diego mode), and run smoke tests.
- Deployment :heavy_check_mark: 
- Smoke test :heavy_check_mark:
> fix: kubecf#1181. Have rep set kernel parameters

- .commitsar.yaml
- .github/workflows/conventional-commits-lit.yml
This new GH action will check if the pull request message follows the conventional commit standards. 
It will happen only to the pull request message and not for the commits within since the commitsar configuration file is explicitly disabling it.
To help the reviewer (or anyone else) to immediately understand the type of pull request and it's the first step to support a better and more efficient release notes process.
fixes #624.
N/A
N/A
> feat: add conventional GH action

- chart/templates/_config.tpl
- tests/config/templates/lookup.yaml
The documentation says:
> Lookup $path under $context and return either the value found, or the empty string.
However, if along the path there is an empty map or slice, lookup would return this map or slice, even though should have been more path elements to traverse.
This commit fixes the logic to set `$.kubecf.retval` to `nil` and return an empty string instead. The only time when _config.lookup should return `{}` or `[]` is when the value **at the end of the path** exists and is an empty map or slice.
> Return empty string when looking up non-existing properties

- chart/values.schema.yaml
- chart/values.yaml
It doesn't hurt to add the `loadBalancerIP` key to `values.yaml`, eh? Actually, it helps a lot when discovering it.
I went to make sure what was the correct syntax to specify a static IP for the load balancer and I realized we were missing it in the `values.yaml`.
It has not been tested, the change is simple enough to not require that. It's all about being explicit.
> fix: missing loadBalancerIP on values.yaml

- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_grootfs_utils.sh
- chart/assets/operations/instance_groups/diego-cell.yaml
- chart/config/unsupported.yaml
- chart/templates/NOTES.txt
- chart/templates/_config.tpl
- chart/values.yaml
Diego cells no longer use a PVC. They will use EmptyDir storage from the host node.
The host node will need to have sufficient disk space to host the cell.
The amount of disk used by grootfs is calculated using the amount of ephemeral storage configured for the cells.
Fixes #489 
Fixes #1241 
Ran locally.
> fix: diego cells should use EmptyDir storage by default

- .github/workflows/conventional-commits-lit.yml
Rename the GitHub action name to something more suitable.
The current GitHub action is bringing some confusion special with the _lint_ word on it.
N/A
N/A
> fix: Rename GitHub action that validates the PR title semantics.

- scripts/kubecf-wait.sh
The `dm` qjob doesn't appear to exist anymore with the new operator; drop it when waiting for the deployment.
The script never finishes waiting (or rather, it eventually times out).
Ran locally.
> fix: scripts/kubecf-wait: no longer wait for dm

- scripts/image_list.rb
This adds support for the `VALUES` override when building the image list.  This is helpful when testing local changes to be able to customize the list of images that will be needed (so they can be traferred to the kubernetes cluster).  This should not be used in CI builds.
Note that most of the changes are to make rubocop happy.
While working on #284 I needed to set an override for the image for a new thing that we are not publishing yet (to use my WIP image).  That means I need to provide overrides, but that wasn't possible with the way we were doing the image list.
Ran locally, and loaded all the resulting images into minikube.
> feat: scripts/image_list: support VALUES override

- scripts/image_list.rb
The default release name (since the stacks change) is now `$defaults` rather than defaults.
Addresses https://github.com/cloudfoundry-incubator/kubecf/pull/1290#discussion_r483275140
Ran locally, generating an image list that I used to load images into minikube.
> fix: image_list.rb: use $defaults for release name

- .concourse/pipeline.yaml.gomplate
Size was too large
Using local node storage for cells.
Pipeline already flown.
> Limit disk usage during tests to 60GB

- chart/assets/operations/sizing.yaml
- chart/templates/bosh_deployment.yaml
- chart/templates/ops.yaml
- chart/values.schema.yaml
This adds the ability to set [tolerations] on the instance groups, to be able to do things such as allocating diego-cell pods on separate kubernetes nodes.
Also includes some misc helm template cleanups for readability.  Looking at separate commits is recommended.
Note that I'm doing this under `.Values.sizing`, as `.Values.sizing.*.affinity` is already a thing (even though it makes no sense).  We should add a migration to rename that to `.Values.instance_groups`, I think.
[tolerations]: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
Fixes #607
Deployed with a toleration:
```yaml
sizing:
nats:
tolerations:
- key: "key"
operator: "Equal"
value: "value"
effect: "NoSchedule"
```
Examined the pod after deployment. (This has no effect, as there are no nodes in my …
> feat: Add tolerations for instance groups

- chart/assets/operations/instance_groups/api.yaml
- chart/assets/operations/instance_groups/eirini-helm.yaml
- chart/templates/_config.tpl
- chart/templates/_stacks.tpl
- chart/templates/database.yaml
Just adds some newlines and a separator in front of the message.
So instead of
```
[...]-eirini-tls-client-cert\n\n# Remove the whole diego-cell instance group.\n- type: remove\n  path: /instance_groups/name=diego-cell\n\n# Remove bbs from diego-api.\n# TODO: remove bbs in the future - when the clock and worker no longer need it.\n# - type: remove\n#   path: /instance_groups/name=diego-api/jobs/name=bbs\n\n# Remove auctioneer, tps and ssh_proxy from scheduler.\n- type: remove\n  path: /instance_groups/name=auctioneer\n- type: remove\n  path: /instance_groups/name=scheduler/jobs/name=tps\n- type: remove\n  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy\n\n# For eirini-extensions: Add hostname-only names to the CC/UAA certificates\n- type: replace\n  path: …
```
> fix: define _config.fail template for more readable error messages

- .github/workflows/conventional-commits-lit.yml
Currently, the pull requests from fork repositories are not triggering the title validation GitHub Action.
In August, GitHub [released](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) fork support for the GitHub Actions and by replacing the trigger from pull_request to _pull_request_target is now possible to perform pull request title validation through the existent GH action.
Tested on a side project by opening a pull request from a fork repo.
> fix: replace pull_request trigger with pull_request_target to include forks

- chart/assets/operations/instance_groups/nats.yaml
The `nats.service.cf.internal` is defined in https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L320-L326 , but a duplicated alias name is added here: https://github.com/cloudfoundry-incubator/kubecf/blob/master/chart/assets/operations/instance_groups/nats.yaml#L2-L11 , that causes the generated manifest yml file contains two `nats.service.cf.internal` in secret `with-ops` as below:
```
- domain: nats.service.cf.internal
targets:
- deployment: cf
domain: bosh
instance_group: nats
network: default
query: '*'
- domain: _.nats.service.cf.internal
targets:
- deployment: cf
domain: bosh
instance_group: nats
network: default
query: _
- domain: log-cache.service.cf.internal
targets:
- deployment: cf
domain: bosh
instance_group: log-cache
network: default
query: '*'
- …
```
> Remove the extra nats.service.cf.internal dns alias

- .concourse/pipeline.yaml.gomplate
Right now, things consuming from GH release artifacts expect artifacts with `v` before the semver.
We have added `v` manually for kubecf-v2.4.0.tgz and kubecf-bundle-v2.4.0.tgz.
This changes the publish job of the concourse pipeline to release artifacts with `v` in it, so we will not need to do it manually on following releases.
This is the easy fix: no need to change consumers of GH releases (kubecf, CAP pipelines, etc) nor docs.
Manually running the sed command.
> fix: Add back v before semver into published artifacts

- .concourse/tasks/upgrade.sh
Analogous to https://github.com/cloudfoundry-incubator/kubecf/pull/1285, for the upgrade job.
We hit the limit on /var/vcap/data grootfs for the node when perfoming upgrades. This solves it.
Manually testing upgrade jobs out of CI. Since this is in ` .concourse/tasks/upgrade.sh` and not a pipeline definition, there's nothing to be flown for the kubecf pipeline.
> fix: Limit disk usage during tests to 60GB also in upgrade job

- mixins/eirini/templates/routing.yaml
Eirini-routing will just crash repeatedly if it can't reach NATS.  So actually annotate that so we can reduce the number of crashes on startup (hopefully to make things run faster since we don't need to restart pods all the time).
My `eirini-routing` pod was crashing a lot on startup.
Deployed with eirini on minikube.
> fix: eirini-routing: wait for nats

- bosh/releases/pre_render_scripts/diego-cell/silk-cni/jobs/patch_cni-wrapper-plugin.conflist.sh
- chart/assets/operations/instance_groups/acceptance-tests.yaml
- chart/assets/operations/instance_groups/diego-cell.yaml
- chart/config/releases.yaml
- chart/templates/apps_dns.yaml
- chart/templates/service_discovery_controller.yaml
- chart/values.yaml
Integrates https://github.com/SUSE/kubecf-apps-dns with KubeCF. This enables DNS-based Service Discovery for apps, replacing the `bosh-dns-adapter`.
Fixes https://github.com/cloudfoundry-incubator/kubecf/issues/776.
`bosh-dns-adapter` is not suitable to use with our current CoreDNS-based solution. The approach presented in this PR was initially posted in https://github.com/cloudfoundry-incubator/kubecf/issues/776.
Followed the instructions on https://github.com/cloudfoundry-attic/cf-networking-examples/blob/8e3be5faa135746cfd1e05bc618fe18053eab2b5/docs/c2c-with-service-discovery.md#use-case-1-frontend-connects-to-single-backend.
> feat: add apps-dns

- .concourse/suse-buildpacks-ci/buildpack-version-bump/config.yaml
- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/config.yaml
- .concourse/suse-buildpacks-ci/stemcell-version-bump/pipeline.yaml.gomplate
- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/prep.sh
The SUSE buildpacks and stemcell information was moved from `values.yaml` to `chart/config/sle15.yaml`. The stemcell and buildpack update pipelines were adapted accordingly.
The replacement is a simple regex to reduce complexity of the pipelines and save time since we might implement #1109 in the nearby future so it is not worth covering every corner case.
Since the stemcell pipeline triggers every time there is a new stemcell I do not think it is necessary to handle different stemcell versions for each buildpack.
The pipelines were updated manually and ran against current master. Since all buildpacks and the stemcell are already up to date there were no changes to commit yet.
> fix: Adapt pipelines to new path

- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
Fix shellcheck lint errors in __.concourse/suse-buildpacks-ci/__
Appears to have been introduced in https://github.com/cloudfoundry-incubator/kubecf/pull/1315
I've run `make lint` locally, but I haven't tested nor flown the changes to the pipelines.
> fix: Fix linting errors in .concourse/suse-buildpacks-ci

- .concourse/pipeline.yaml.gomplate
Actually run CATS with eirini config in CI. We were using the default config of cats with `KUBECF_TEST_SUITE=cats`.
We should be using `KUBECF_TEST_SUITE=cats-eirini`, which will patch the cats config.
Running locally with `KUBECF_TEST_SUITE=cats-eirini`, and attempting to fly the pipeline (without flying) to see that the change only affects the `cf-acceptance-tests-eirini-*` jobs in concourse.
> fix: Actually run CATS with eirini config in CI

- chart/values.yaml
Without this change, setting annotations of `services.foo.annotations` on up to helm 3.3.1 gives the
following warnings on helm install/upgrade:
```
secret/susecf-scf.var-cf-admin-password created
secret/var-cf-admin-password created
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring …
```
> fix: Change services.foo.annotations to {} from ~

- chart/assets/operations/instance_groups/diego-cell.yaml
- chart/assets/operations/instance_groups/scheduler.yaml
In order to support apps DNS, we changed the TLS certificate host name for the service discovery controller.  However, we need to move it to a place where it's used for Eirini as well; move it to the scheduler group (where the service discovery controller lives) instead.
Eirini apps failed to deploy, because we couldn't upload to the blobstore (on account of DNS being hosed).
Deployed apps on eirini.
> fix: apps-dns: change certs when using eirini

- mixins/eirinix/config/eirinix.yaml
- mixins/eirinix/templates/loggregator-bridge.yaml
Should fix https://github.com/cloudfoundry-incubator/kubecf/issues/923 . As now the loggregator-bridge ships an extension, adding the related services/options.
https://github.com/cloudfoundry-incubator/kubecf/issues/923
Locally
> fix: bump loggregator-bridge version

- chart/assets/scripts/jobs/pxc/seeder.sh
- chart/templates/database.yaml
- chart/values.yaml
- Added timeout to `values.yaml`. Already handled by the schema, generically.
- Added templating to database, propagating the data in the `values.yaml` into the pod environment.
- Extended the seeder script to use the value from the environment.
#1191 
:warning: On looking at the modified code I am not sure why a configurable timeout is needed. The command where the timeout applies is wrapped into a loop which repeats forever until the database is ready. Regardless of timeout used AFAICT.
As such I am not sure of the original diagnosis in #1191 :warning:
Used a minikube to deploy kubecf, with the new key set to
```
features:
embedded_database:
connect_timeout: 10
```
and inspected the generated kube object to verify that
- It contains the value in the proper/new environment variable.
- …
> feat: Configurable database seeder connection timeout

- chart/templates/ingress.yaml
In the public services (used when we're not using ingress), don't have a version label in the selector when finding backends.  This is necessary to ensure that, during upgrades, we can select for whichever pod happens to be running at the time (including the old version).  Otherwise we'll unnecessarily introduce downtime as we refuse to connect to the perfectly fine pods (from the previous version).
The same logic also applies to downgrades (where the working pods are from a newer version).
For https://github.com/cloudfoundry-incubator/kubecf/issues/1257 - but this might not fix the whole thing (as the database is still not properly HA).
Deployed locally on a HA cluster.
> fix: chart: public svcs: don't select on version

- .concourse/pipeline.yaml.gomplate
- .concourse/tasks/upgrade.sh
Limit diego-cell's ephemeral_disk to 40000 in CI.
Consume catapult's changes to upgrade cf-operator too on kubecf-upgrade.
Validate a kubecf upgrade by running smokes afterwards in Concourse's upgrade job.
To fix the upgrade job.
Amalgamates:
https://github.com/cloudfoundry-incubator/kubecf/pull/1335
https://github.com/cloudfoundry-incubator/kubecf/pull/1332
Tested successfully in job https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad/jobs/upgrade-test-limit-disk-usage-ci/builds/6 .
Compared catapult's history between the previously pinned hash and this one, no additional changes needed to CI.
> fix: Fix Concourse upgrade job by changing disk size and upgrading cf-o

- chart/templates/_helpers.tpl
- chart/values.schema.yaml
- chart/values.yaml
- mixins/eirinix/config/eirinix.yaml
- mixins/eirinix/templates/dns-aliases/deployment.yaml
- mixins/eirinix/templates/dns-aliases/service.yaml
This adds the [eirini-dns-aliases](https://github.com/SUSE/eirini-dns-aliases) eirini extension; it causes the application containers (as in, things deployed with `cf push`) to use the BOSH DNS resolver instead of the default Kubernetes one.
Fixes #284
- Deployed locally, with eirini
- From an application container, `curl -kv https://credhub:8844`
- Resolving `credhub` (to `credhub.service.cf.internal`, then to an IP address) was only possible because of the extension.
- We may want to wait for #1259 to land first, and then rebase this on top of that work.
- This needs to wait for https://github.com/SUSE/eirini-dns-aliases/pull/1 to be merged first.
- This will affect https://github.com/cloudfoundry-incubator/kubecf/issues/776 — but that should just mean `DNS_SERVICE_HOST` from …
> feat: Implement eirini-dns-aliases

- chart/templates/database.yaml
Reworked the templating logic to check `features.high_availability` after `sizing.database.instances` before falling back to the minimum default.
See #1333 
Deployed to local minikube for all possibilities, i.e. SA, HA, explicit sizing (with HA, to verify that sizing has precedence).
> fix: Modified database template to handle `features.high_availability`.

- chart/assets/operations/instance_groups/api.yaml
- chart/assets/operations/instance_groups/diego-api.yaml
- chart/assets/operations/instance_groups/router.yaml
- chart/assets/operations/instance_groups/scheduler.yaml
- chart/assets/operations/instance_groups/tcp-router.yaml
fix the loggr-udp-forwarder incorrect INDEX issue.
https://github.com/cloudfoundry-incubator/kubecf/issues/1337
Environment
cf-operator: 5.2.0
kubecf: v2.2.3
apply the fix code and deploy kubecf with multi_az="true"(2 azs) and instance=1.
after all pod up and running,
check container loggr-udp-forwarder-loggr-udp-forwarder's environemnt INDEX and IP.
for example:
```
$ k exec -it scheduler-z1-0 -n kubecf -c loggr-udp-forwarder-loggr-udp-forwarder  sh
sh-4.4# printenv |grep INDEX
AZ_INDEX=2
INDEX=scheduler-z1-0
sh-4.4# printenv |grep IP
IP=x.168.119.18
```
cf-operator: 5.2.0
> fix: loggr-udp-forwarder  incorrect 'INDEX' and 'IP' environment

- chart/templates/database.yaml
Start of liveness checks is delayed longer to give the database (in resource-constrained environments) the time to come up properly instead of getting killed by kube as not-live.
See #1128 
Reproduction of the original issue on a minikube was only semi-successful. 
It was necessary to set `initialDelaySecond: 1`, `timeoutSeconds: 1`, and `failureThreshold: 1` to get a deployment where the database was restarted a few times instead of getting up smoothly. Even then the environment was good enough to recover and get the pod fully started.
That said, even with this limited reproduction it is clear that bumping the `initialDelaySeconds` should have a positive effect in more constrained environments.
Conversely it is recommend that a person who had the original issue reviews and verifies the …
> fix: Bumped db liveness initial delay to 5 minutes.

- chart/generate-minions-values.sh
- chart/templates/multiple_cluster_mode.yaml
- chart/values.yaml
- doc/multi-cluster.md
When deploying kubecf in multi_cluster mode, failed with the error:
```
2020-09-10T06:19:51.473Z	ERROR	boshdeployment-reconciler	boshdeployment/deployment_reconciler.go:121	failed to list quarks-link secrets for BOSHDeployment 'kubecf/kubecf': missing link secrets for providers: cloud_controller_container_networking_info, cf_network
```
To fix the missing  link error in multi-cluster mode.
Tested in IBM multi cluster.
> fix: missing links in multi_cluster mode

- chart/config/releases.yaml
Bumps the brain tests to the latest version that removes the Minibroker-related suites.
Also, bumped the stemcell from 27.4 to 27.5.
Brain tests don't assert the Minibroker functionality anymore, this is done by the MITS.
CI shall do.
I verified that the images exist for the releases we include out of the cf-deployment.
> feat: brain tests 0.0.14

- chart/templates/apps_dns.yaml
This PR fixes upgrades from KubeCF 2.5 to _next_.
```
Error: UPGRADE FAILED: cannot patch "apps-dns" with kind Deployment: Deployment.apps "apps-dns" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"apps-dns", "app.kubernetes.io/instance":"susecf-scf", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"susecf-scf-kubecf", "app.kubernetes.io/version":"0.2.0-1952.g99e5ce80", "helm.sh/chart":"kubecf-0.2.0-1952.g99e5ce80"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
> fix: mutating deployment selector on apps-dns

- chart/assets/operations/instance_groups/diego-api.yaml
This PR fixes two issues in the locket readiness check:
1. The `locketAPILocation` should be `127.0.0.1` instead of `localhost` as `localhost` is not set in the locket server certificate 
```
X509v3 Subject Alternative Name:
DNS:*.locket.service.cf.internal, DNS:locket.service.cf.internal, IP Address:127.0.0.1
```
After change to `127.0.0.1`, we can remove `--skipCertVerify` in the `cfdot` command
2. According to BOSH deployed CF, the `cfdot` command should use the certificates from itself, not from locket server.
See `/var/vcap/jobs/cfdot/bin/setup` which sets environment variables for `cfdot`
```
#!/usr/bin/env bash
if ! echo $PATH | grep -q 'cfdot'; then
export PATH=/var/vcap/packages/cfdot/bin:$PATH
fi
export BBS_URL=https://bbs.service.cf.internal:8889
export …
```
> fix: locket readiness check

- chart/README.md
The link to the operator docs is incorrect in the chart README.
Encountered while doing #629 (because I tried to follow the link).
Navigated to the links.
> fix: chart: update operator docs links

- chart/config/unsupported.yaml
- scripts/image_list.rb
Add explicit check for non-sensical database configurations (no database at all, or multiple database options).
This will need to be adjusted once we review our configuration options to reduce chances of creating unusable combinations.  This would be in an issue that will be spawned from #1086.
While trying to implement #629 I was confused by our database configuration and wanted to make sure I'm covering the necessary cases.
Rendered the configuration in the following cases:
Config | Supported?
-- | --
embedded only | ✅ 
external only | ✅ 
embedded + external | 🚫 
none | 🚫 (except in multi-cluster cell mode)
I expect I'll need to expand the documentation around our database options once #629 has progressed more.
I don't particularly like the line folding around line 18, but the condition …
> feat: chart: Error out on unsuported db configs

- .concourse/tasks/upgrade.sh
Consume kubecf-bundle tgz in upgrade, not kubecf tgz
Fix the upgrade job, which is missing the bumps of cf-o as it is not consuming the new kubecf-bundle.tgz for the upgrade.
It hasn't been tested. Needs to be merged in master to be consumed by the pipeline.
> fix: Consume kubecf-bundle tgz in upgrade, not kubecf tgz

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
The latest changes to the GitHub templates for some reason made the templates useless 'cause they are not being triggered since then.
To have the Bug and Feature templates back to the game.
Nope.
N/A
N/A
> fix: remove the validation label

- .concourse/tasks/upgrade.yaml
Consume s3.kubecf-ci-bundle as input in upgrade task, instead of s3.kubecf-ci.
Fix upgrade job.
It has not. Needs to be in master for it to run.
> fix: Consume s3.kubecf-ci-bundle as input in upgrade task

- chart/config/api.yaml
- chart/templates/_config.tpl
- scripts/helmlint.sh
Added ops instructions setting the CAPI cc_ng properties controlling the values to be returned by the endpoints `info`, `v2/info`, and `v3/info`.
See #1367 
Deployed on minikube, logged inot CF, then used `cf curl ENDPOINT` for the endpoints above and checked that the values are not empty anymore, and the expected.
> fix: Add missing data for the CF info endpoints.

- .concourse/pipeline.yaml.gomplate
Concourse pipeline doesn't create a DNS record for the ssh-proxy service so all requests to ssh.$DOMAIN find the router instead. This should fix the failed ssh tests on Eirini CATs.
We need green Eirini CATs
Pipeline already deployed here: https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-eirini-master/builds/51
> fix: add dns record for ssh_proxy (both diego and eirini)

- .concourse/pipeline.yaml.gomplate
Create normal GKE clusters instead of preemptible ones on Concourse
Say bye to losing 5-15% of clusters.
Not tested.
Not flown.
> fix: Create normal GKE clusters instead of preemptible ones on Concourse

- chart/assets/operations/instance_groups/credhub.yaml
Credhub otherwise advertizes to the client the internal url that can't be resolved:
```
Setting the target url: https://credhub.172.18.0.2.xip.io
Warning: The targeted TLS certificate has not been verified for this connection.
Warning: The --skip-tls-validation flag is deprecated. Please use --ca-cert instead.
UAA error: Post https://uaa.service.cf.internal:8443/oauth/token: dial tcp: lookup uaa.service.cf.internal on 10.96.0.10:53: no such host
```
This problem doesn't seems to hit our test suites because they are bosh releases which are started with cfo, that injects the bosh dns server to the instances.
This changes sets the internal and external url of uaa in credhub correctly, so that the config yaml in the credhub pod results in the following:
```yaml
/:/var/vcap/jobs/credhub# cat …
```
> fix: Add internal/external credhub url

- chart/config/unsupported.yaml
- chart/templates/_config.tpl
- chart/values.schema.yaml
This PR blocks the use of --reuse-values when upgrading from 2.5.0 or earlier because those release may include release-specific information (image names and versions etc), or may have persisted changes made by the templating code.
Upgrades from 2.4.0 and earlier are blocked via an `unsupported` rule that checks for the `eirini.env.DOMAIN` property that has been removed in 2.5.0.
Upgrades from 2.5.0 using `--reuse-values` are blocked via schema validation that does not allow limits or requests to be `nil`. Upgrades from 2.5.0 using the existing `values.yaml` file are not blocked and should be benign as the version specific settings have already been moved to `config/*.yaml` files.
We have run into problems with `--reuse-values` in our own CI and we want prevent users from running into the …
> fix: limit reuse of config values

- chart/config/resources.yaml
This is the same default we already use for all regular processes that don't have an explicit limit defined.
We've seen at least the syslog forwarder getting occasionally OOMKilled with the 32Mi limit.
> fix: Increase default memory limit for addon processes from 32Mi to 64Mi

- .concourse/pipeline.yaml.gomplate
Fix the files expected by s3 Concourse resources.
Artifacts get the `v` added, even if it isn't in semver, to be consistent with
the history of artifacts we have.
Closes https://github.com/cloudfoundry-incubator/kubecf/issues/1412.
Already flown, see passing jobs: (I deleted artifacts manually to be able to retrigger the job)
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/publish-master/builds/26.3
> fix: Publish tgzs correctly in release job

- .concourse/pipeline.yaml.gomplate
This reverts commit 994e34f780f7211e26a176163cc1085edc469958.
That commit was added because we mangled the semver for 2.5.0 and included a git
hash in it. Hence, for releasing the tar, we removed the `g<hash>` part too. We
should have not done that, and the job was failing correctly.
Now, with 2.5.1, the semver doesn't contain the git hash, so we shouldn't try to
remove it. This is the correct behaviour.
Fix publish job on release-2.5 branch.
Already flown.
> fix: Revert "fix: Remove also the git part from the version of the artifacts"

- chart/config/resources.yaml
After running a cluster for 8+ hours, I noticed all doppler replicas getting restarted multiple times due to memory limit enforcement.
> fix: doppler OOMKilled

- mixins/eirinix/templates/loggregator-bridge.yaml
because DEBUG prints out every single message that has to be sent:
https://github.com/cloudfoundry-incubator/eirini-loggregator-bridge/blob/7da9e0471e531968771b6237267762f074e40f29/podwatcher/loggregator.go#L45
DEBUG log level should only be used when debugging, not in production. Reduce it to INFO.
> fix: Reduce the log level of eirini loggregator bridge

- chart/assets/operations/instance_groups/rotate-cc-database-key.yaml
- chart/config/resources.yaml
- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
Set a memory limit on the CCDB key rotation job, so that it has enough resources to run.
From experimenting locally on a minikube:
- a limit of 128Mi is not enough to run
- a limit of 192Mi is enough to run.
So I'm picking a request of 192Mi, and a limit of 512Mi just in case (it should never get that high anyway).
I'm also disabling the log sidecar for that job, since it's a job and having the sidecar just means it'll never complete.
CI was failing.  Not sure @viovanov ever filed a bug on it.
Ran the job locally (manually triggering the QJob) until it passed.
> fix: CCDB  secret rotation: set explicit resource limits

- .concourse/pipeline.yaml.gomplate
Unblocks https://github.com/cloudfoundry-incubator/kubecf/pull/1430
Tested successfully against #1430.
Already flown (to be merged directly).
No additional changes on the bump.
> fix: Bump catapult on Concourse CI on release-2.5

- chart/values.schema.yaml
Catapult (used to) add additional properties under the `kube` key that are completely ignored by kubecf.
It is my understanding that these settings have been removed from catapult, so we should tighten the schema so it will catch misspelled property names provided by actual users.
> fix: Remove allowance for old catapult cruft

- .github/workflows/pull-request-queue.yaml
This temporarily disables the automatic triggering of builds / tests; we are currently not using them to block merges.  Leave it possible to manually trigger runs, so that we can continue to develop GitHub Actions until we can require them to pass before merging (replacing Concourse).
We can revert this once GHA can be used as the only CI.
We're running out of GKE quota for CI we need for releasing.  We're not currently blocking merges on GHA anyways.
N/A
> feat: GitHub Actions: disable automatic triggers

- chart/assets/operations/instance_groups/diego-cell.yaml
- chart/templates/NOTES.txt
When we're using PVCs for ephemeral disks for diego-cell, we will need to set the disk size.  The default size of 10Gi is too small to hold the default (grootfs) disk size.  Calculate it based on the user-specified ephemeral disk size, so that it can adjust according to user needs.
It needs to be slightly larger than the user specified size, as it is also used to hold other internal data; as an initial estimate, make it 5Gi larger than requested.  We may be able to adjust this down later, as for initial deployment we appear to only need <300Mi extra.
Fixes #1451
Deployed on AKS in a situation that lead to the discovery of #1451 in the first place.
Checked that we have a generated PVC of 45Gi (when the default is 40Gi).
- By basing it on the existing size, we do not need to change the …
> fix: set diego-cell ephemeral PVC disk size

- chart/templates/rbac.yaml
Both are used by the rep in the diego-cell.
Fixes #1423
> fix: Add NET_ADMIN and NET_RAW to PSP

- chart/templates/database/db-statefulset.yaml
Don't use the full labels (including the version) for the selector for the database.
Thulio (@f0rmiga) noticed that we were using the version in the selector for the database.
Rendered the template and checked that the selector was correct.
> fix: db: fix selector

- chart/assets/operations/instance_groups.yaml
Add the standard labels to the generated QuarksStatefulSets, so that we can see the version when examining a live deployment easier.  The selector are unaffected, as we want to be able to use the previous version for a bit during an upgrade.
When examining an upgrade, it is difficult to figure out what version of KubeCF corresponds to each pod.
Deployed during an upgrade (HA). I have confirmed that:
- The StatefulSets are updated, not recreated (their creation timestamp is from before the upgrade took place).
- The existing pods are rolling as expected — `api-1` is upgraded and ready before `api-0` is upgraded.
(Actually, the upgrade never completes because `api-1` is not counted for bootstrap, so DB migration never takes place, and therefore `api-1` can never get ready.  But that's an …
> feat: chart: add labels to QuarksStatefulSets

- bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
Allow for rhel/centos distributions to be able to run update-ca-certificates.
A case entry:
```
+ *rhel|centos*) 
+ timeout --signal=KILL 180s /usr/bin/update-ca-trust -f -v 
+ cp /etc/ssl/certs/ca-bundle.crt ${OS_CERTS_FILE} 
+ ;;
```
to be added to:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
At the moment in order to be able to run on OpenShift, we are manually updating `uaa_uaa_patch_pre-start_sh.yaml` to include a case for `rhel|centos` during update-ca-certificates. For every release of kubecf, this requires us to unpackage kubecf artifact, apply the fix, and repackage it back up again.
Related issue: https://github.com/cloudfoundry-incubator/kubecf/issues/1447
After manually adding the patch, we are …
> feat: add case for rhel|centos during update-ca-certificates

- scripts/image_list.rb
Only disable cflinuxfs3 when Eirini is enabled. Otherwise we will be missing all the default stack images.
> fix: Use default stack list to compute imagelist.txt

- chart/config/releases.yaml
Brings in a fix for the 005/metron test to handle the differences
between diego and eirini app logs.
See #1371 
Local minikube.
> fix: bump brain test release to v0.0.15

- chart/config/unsupported.yaml
- chart/templates/_features.tpl
- chart/values.schema.yaml
- chart/values.yaml
- scripts/image_list.rb
- `routing_api.enabled` flag defaults to `nil` now.
- Feature config handling now sets proper default per chosen scheduler.
- Rejects user trying to force `eirini` + `routing_api`.
- Values schema updated (now allowing `nil` for the enabled flag)
- `image_list.rb` script skips the forbidden permutation.
See #1371 and discussion in #1445 
Local minikube
> fix: disable routing api under eirini, not supported

- chart/templates/_config.tpl
There is a chance of dataloss when we upgrade from HA to SA while also changing the chart version. And we no longer support an embedded HA database, so the user has to scale down before performing the upgrade.
Eventually this code (together with the "unsupported" logic) should be moved to its own template file.
> fix: Don't allow upgrades unless the embedded database is a singleton

- .concourse/suse-buildpacks-ci/releases.yaml
The sle15 stack was not automatically updated. The buildpack releases are handled the same way as the stack so we can reuse the buildpack pipeline to update the stack automatically in the future.
The pipeline was updated and the resulting pr branch #1473 works locally. Only the Docker registry needs to changed once because we will not use dockerhub anymore.
> fix: Add sle15 stack to stemcell-pipeline

- mixins/eirini/config/eirini.yaml
- mixins/eirini/templates/configmap.yaml
Added the capability to configure servicaccountname for eirini staging job and eirini apps.
Add to default eirini configuration the entry `staging_service_account` for configuring eirini staging job serviceaccount name. Also updated to allow same configuration for `application_service_account` in default eirini configuration for consistency.
We’ve been trying to test kubecf 2.5.8 and noticed that the eirini staging jobs doesn’t use `serviceAccountName: eirini` anymore and also annotation `seccomp.security.alpha.kubernetes.io/pod: runtime/default` has been added. Since we’re running on OpenShift, the setting of the annotation causes permission denied errors and we can’t fix this because there’s no `serviceAccountName` to configure/attach a SecurityContextConstraints for.
It was suggested …
> feat: added capability to configure staging serviceaccount name

- chart/config/releases.yaml
- chart/templates/_helpers.tpl
- chart/templates/patch_serviceaccount.yaml
- chart/values.schema.yaml
- chart/values.yaml
- mixins/bits/templates/bits-service-account.yml
- mixins/eirini/templates/events-service-account.yml
- mixins/eirini/templates/metrics-service-account.yml
- mixins/eirini/templates/routing-service-account.yml
- mixins/eirini/templates/serviceaccount.yaml
- mixins/eirini/templates/staging-reporter-service-account.yml
- mixins/eirinix/templates/eirinix-serviceaccount.yaml
Allow users to define a list of imagepullsecret names allowing kubecf to pull from private registries requiring authentication.
Allow users to define a list of imagepullsecret names. Secrets would have to be created prior. These imagepullsecret names are then added to the serviceaccounts used by kubecf, allowing kubecf pods to pull from private registries requiring authentication. The serviceaccounts updated are:
```
default (namespace kubecf)
eirinix
opi
eirini-events
eirini-metrics
eirini-routing
eirini-staging-reporter
```
The `default` serviceaccount is updated with imagepullsecrets using helm/pre-install method. While the rest are updated by adding the entries to each of the corresponding template serviceaccount.
Allows kubecf to pull from private registries requiring authentication. …
> feat: pull kubecf from a private registry requiring authentication

- scripts/cf-operator-delete.sh
These are catapult functions that are not defined in kubecf. They are wrappers that work with both helm 2 and helm 3, but the kubecf scripts all require helm 3, so this isn't necessary.
Also don't hardcode the operator namespace, but use the proper config variable.
> fix: Inline helm_ls and helm_delete

- .concourse/suse-buildpacks-ci/buildpack-version-bump/pipeline.yaml.gomplate
- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build.sh
- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build.yaml
- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
- .concourse/suse-buildpacks-ci/stemcell-version-bump/pipeline.yaml.gomplate
- .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
Build images of updated buildpacks against the stemcell specified in sle15.yaml instead of taking the latest released stemcell.
The stemcell is update in a separate pipeline called `suse-buildpacks-stemcell-version-bump`.
This change should prevent race conditions specified in #1164.
The pipeline was deployed and did already run successful.
> fix: Build updated buildpacks against the stemcell specified in sle15.yaml

- chart/assets/operations/instance_groups/eirini-helm.yaml
These settings are not needed, and they will break when kubecf is configured to use an external blobstore because then the singleton-blobstore service doesn't even exist.
I suspect that more settings in this file are redundant, but want to have a minimal change to just fix Eirini with external
blobstore deployment.
I've only tested that Eirini continues to work on minikube. I have not tried to deploy with an external blobstore, so there may still be other undiscovered issues.
> fix: Remove blobstore settings from eirini-helm ops file

- .github/workflows/pull-request-ci.yaml
This forces the use of Python 3.8 when running GitHub Actions (for catapult, needed by the Google Cloud SDK).
The latest available google-cloud-sdk (315.0.0) is not yet compatible with Python 3.9.  There's a tracking bug at https://issuetracker.google.com/issues/170125513.
This was discovered while working on  #1144.
Ran a build on my fork, ensuring that the build proceeds past having a working Kubernetes cluster.
> fix: Actions: force use of Python 3.8

- chart/templates/ingress.yaml
Updates to ingress.yaml that allow the pod selector to match the scheduler pod in KubeCF.
This is to address #1509 , where `ccf ssh` to apps does not work in cases where the ssh-proxy-public service uses a LoadBalancer instead of an nginx ingress-controller.
The scheduler pod has a label called `app.kubernetes.io/component=scheduler`
Whereas the service resource described in ingress.yaml, specifies a pod selector with a value `app.kubernetes.io/component=ssh-proxy`
The pull request modifies the label and the pod selector to `app.kubernetes.io/component=scheduler`, such that the service can match the ssh-proxy container in the pod
This change allows the ssh-proxy-public service to select the appropriate kubecf pod, and enables the `cf ssh` capability to work when the services are deployed …
> fix: Update ingress.yaml

- chart/config/sle15.yaml
The 24.81 rootfs has only been build with the previous 27.8 stemcell. This issue will self-correct once there is another update to the rootfs, which happens pretty frequently.
> fix: downgrade sle15 rootfs because the latest image does not exist

- dev/kube/klog.sh
Remove the `--export` flag from `kubectl get` invocations in `klog.sh`, because it has been removed.  See https://github.com/kubernetes/kubernetes/pull/73787
Trying to run `klog.sh` is failing for me:
```
Pod cf-operator-7b966b9dcf-tlvn8 = Running
- job  cf-operator logs: Kube
Descriptions ...
Pod cf-operator-quarks-job-cc575c654-sqspf = Running
- job  quarks-job logs: Kube
Descriptions ...
Pod cf-operator-quarks-secret-5959c95c49-hvqzb = Running
- job  quarks-secret logs: Kube
Descriptions ...
Global information...
Resources ...
Error: unknown flag: --export
See 'kubectl get --help' for usage.
Error: Process completed with exit code 1.
```
Ran `klog.sh` on my minikube cluster to make sure I still get events.
> fix: klog.sh: drop --export flag on kubectl get

- chart/values.yaml
Fix external-database doc url to point to correct location.
Fix `values.yaml` to have the right external-database doc url
Wrong external-database url
Just went and looked for the right doc location
> fix: external-database doc url

- .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build.sh
There are potential race conditions that a stemcell update
is not yet merged to master in which case a in the meantime
updated buildpack is build against the old stemcell and not
the newer one.
With this commit the buildpack is build against both stemcells.
The stemcell was downgraded in the test branch and the pipeline was executed and verified that images were built against both stemcells.
After that the pipeline was run without the downgrade and it was verified that no issue appeared.
https://concourse.suse.dev/teams/main/pipelines/suse-buildpacks-buildpack-version-bump/jobs/build-image-binary-buildpack/builds/18
> fix: Build buildpacks/stack against two stemcells if necessary

- chart/assets/operations/instance_groups/tcp-router.yaml
- chart/templates/ingress.yaml
The clash is in tcp-router and router both exporting port 80/http. Depending on racing in kubecf the wrong endpoint is exposed through the main service.
- Reconfigured the tcp_router job to not listen on 80/http for healthcheck requests any longer, and use custom port 88 instead.
- Modified the health check probe to use port 88.
- Modified ingress as well.
See #1199 
Minikube deployment, diego/SA. Roles are green, passed smoke and brain tests.
Use with ingress not tested.
This still needs testing on AWS, to be sure that the changed port is ok with AWS loadbalancers.
> fix: move tcp-router healthcheck port to avoid clash

- .github/workflows/pull-request-ci.yaml
They deprecated the (in-band) `set-env` and `add-path` commands; now things go to a file instead.
Getting warnings when running Actions.
See [GitHub blob post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).
Ran action while working on #1144
> fix: CI: Remove deprecated set-env/add-path

- .concourse/pipeline.yaml.gomplate
Move Concourse's resource images to ghcr.io/cloudfoundry-incubator to avoid dockerhub bandwidth limits.
Avoid dockerhub.
Already flown.
> fix: Move Concourse resource images to ghcr.io/cloudfoundry-incubator

- chart/assets/operations/instance_groups/app-autoscaler.yaml
- chart/config/cflinuxfs3.yaml
- chart/config/releases.yaml
- mixins/eirinix/config/eirinix.yaml
This PR uses the images on ghcr.io built with the latest stemcell.
The following images still reside on Dockerhub:
```
docker.io/cfcontainerization/coredns
```
Ref #1557
> fix: use images from Github Container Registry

- .github/workflows/README.md
- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-lint.yaml
- .github/workflows/pull-request-schedule.yaml
- .github/workflows/pull-request-schedule/find-jobs.js
- .github/workflows/pull-request-schedule/trigger-builds.js
~This pull request will change our GitHub Actions workflow to include at least the basic tests, to the point where we might start deprecating our Concourse pipelines.~
~For now, though, I just have a design of how we might handle the build triggering and cluster allocation; I'd like some feedback before actually implementing things.   Hence, this is a draft with just markdown changes.  I'll edit the description once we agree and I've implemented it reasonably.~
I am now rescoping this to _just_ the changes described to scheduling the runs; this is already enough of a change that it's a good chunk to review.  Also, I can work on the tests independently of this PR (in my fork, manually triggering runs).
Part of #1144 (but will no longer fix it by itself).
I have been running this in my …
> feat: Improvements to GitHub Actions workflow

- chart/config/resources.yaml
Bump the memory limit for the cloud controller nginx, as well as the blobstore nginx.  As we're only using those limits to prevent runaway memory consumption, this should be safe.  I did not touch the requests.
My CI runs were failing because the containers were being OOMKilled in the middle of the run (which was only discovered upon examining the logs dumped at the end of a run).
Ran CATS &c runs on GitHub Actions; the tests have been passing since the changes.
> fix: chart: bump resource limits

- chart/templates/NOTES.txt
Replaced fixed value of `1` with a ternary returning either `1` or `3` based on the HA flag.
See #1479 
Local minikube. Deploy only as far as needed to see the NOTES.txt in the terminal.
> fix: Check for HA as part of estimating max app count.

- chart/templates/NOTES.txt
Used @jandubois ' proposal to read the HA cell count from the underlying CF manifest, replacing the hardwired `3`.
See https://github.com/cloudfoundry-incubator/kubecf/pull/1591#discussion_r524586598
Local minikube.
> feat: Auto-adapt NOTES.txt to HA changes in underlying CF manifest.

- .concourse/pipeline.yaml.gomplate
- chart/templates/ingress.yaml
If routing-api is not enabled, then remove the tcp-router-public service (when not using ingress).  Otherwise we end up with a service that will never point at anything.
Discovered while working on #1144.
We will never finish waiting for services to be ready if we have a service that can never be ready.
Tested locally (and in the WIP CI stuff); I can actually finish waiting now.
> fix: chart: Axe tcp-router-public if unavailable

- .github/workflows/pull-request-schedule.yaml
Use Vault instead of GitHub Secrets for credentials; this should make it easier for us to change them (as more people have access).
We are attempting to centralize our secrets into a vault instance, so it is under our control.
Ran on my fork, https://github.com/mook-as/kubecf/actions/runs/366810108
This should only be merged after we made sure we add a `VAULT_TOKEN` (GitHub) [secret](https://github.com/cloudfoundry-incubator/kubecf/settings/secrets/actions) that has access to the `cloud-providers` (vault) secret.
> fix: CI: Scheduler: Use vault for secrets

- chart/assets/operations/instance_groups/app-autoscaler.yaml
This drops the BOSH-style control script for the autoscaler golang apiserver, and uses BPM to directly launch the binary.
I suspect I may be missing features in that control script that the IBM folks are using; however GitHub doesn't seem to like me. @aqan213 — would you have some time to take a look?
I suspect that the control script (having been designed for monit) uses a PID file, which doesn't work well when the container restarts.  I'm seeing issues on some deployments (on CI) where that pod gets stuck at an unready state (crashing repeatedly); deleting the pod and letting the deployment spin up a new one works around the issue.
This was cherry-picked out of my branch related to GitHub Actions work for #1144; I haven't had issues related to the autoscaler not being ready since I made …
> fix: autoscaler: Drop control script

- chart/templates/multiple_cluster_mode.yaml
The deployment-name is supposed to be a label on a secret, not an annotation. Without this change the multiple cluster feature doesn't work
See above
Tested using cf-operator 6.1.7 this progressed the deployment past a blocking issue
> fix: deployment-name should be label not annotation

- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-ci/kubecf-gen-config.sh
Various small CI changes to make running tests more stable; see commits for details.
- Skip AKS steps on GKE, etc.
- Bump on GKE cluster size, and use non-preempt for CI.
- They should be cleaned up correctly by the [scheduler workflow](https://github.com/cloudfoundry-incubator/kubecf/blob/master/.github/workflows/pull-request-schedule.yaml), so there's less pressure to keep things cheap in case they get orphaned
- Set up the GKE config directory (the way it is set it catapult), so that `kubectl` can automatically refresh the access token if a build takes a long time (e.g. running CATS).
- The actions need to run against the PR branch, still, so that it checks out the correct source to test against.
- Move the config values generation to a shell script, because it was rather unwieldy
- …
> fix: GitHub Actions improvements

- mixins/eirini/templates/eirini-cluster-role.yaml
- mixins/eirini/templates/metrics-service-account.yml
There is no need to define the Eirini cluster role and role binding when we are not using them.
Also prefixes the cluster roles and rolebindings with the release namespace name to allow installation of multiple instances within the same cluster.
Fixes #1582
> fix: don't define Eirini cluster role when deploying Diego

- .concourse/pipeline.yaml.gomplate
Pipeline has already been flown and is being tested with #1609 right now.
If that PR is all green, then this change can be merged.
> fix: bump catapult to support renamed cf-operator → quarks-operator

- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-schedule.yaml
- .github/workflows/pull-request-schedule/trigger-builds.js
The automated CI runs were not quite working correctly:
- The CI run was removing the wrong label
- The CI run was proceeding even with no labels set
- The scheduler wasn't triggering correctly, because the GitHub Actions provided token cannot be used to trigger further runs.  Workaround is to use a token from the vault.
CI triggering was busted.
Ran on my fork, manually running the scheduler and seeing that:
- `pr-test-queue` was removed
- `pr-test-trigger` was added
- The CI run actually happened
- `pr-test-trigger` was removed again.
As a precaution, I'm only using the token from the vault where necessary; that's to avoid chewing up the API request quota, since the GitHub Actions token should be ephemeral (and hopefully gets a different quota; at least it would be a different user).
> fix: CI: Actions: Fix PR triggering

- chart/templates/_config.tpl
- chart/templates/_multicluster.tpl
- chart/templates/multiple_cluster_mode.yaml
Right now these are just property settings for `api` and `cc-worker` that are set in `chart/config/api.yaml` and `chart/config/jobs.yaml`, but this commit pre-emptively handles all groups that are removed in `chart/templates/multiple_cluster_mode.yaml`.
Ideally this would all be handled by conditions defined in `chart/config/jobs.yaml`, but the required logic becomes too complex, so special-casing this issue seems warranted.
This commit also adds an op for `brain-tests`, which seems to be missing because of an oversight.
This PR should supersede #1543
> fix: avoid generating ops that reference instance groups that don't exist

- .github/workflows/pull-request-ci.yaml
- .github/workflows/pull-request-ci/isolate-network.sh
- .github/workflows/pull-request-ci/override-cats-properties.sh
- testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh
This adds some of the missing parts of the existing concourse-based pipeline to GitHub Actions:
- Runs the brains tests
- Runs the CCDB rotation tests
- Runs the internetless tests (#1148)
This should be the last part of #1144
Deployed & ran on my fork on KubeCF.
- The network policy stuff for internetless tests is from catapult.
- So is the technique for patching the runtime properties for the CATS QuarksJob to run just the internetless suite.
- I changed it a bit so the property patching is separate from what properties to patch; we could perhaps later change the Eirini config generation to use normal + a step to patch the test suites (so that it is more visible).
- I'm splitting out the experimental flags to separate flags, so that it is easier to adjust them individually if needed.
> feat: CI: GHA: brains, internetless, and CCDB rotation

- scripts/cf-operator-wait.sh
The operator has differently named deployments now; update the wait
script to match.  Otherwise we will wait forever (before failing).
My GitHub Actions runs were failing because that uses `make cf-operator-wait`.
Deployed locally.
> fix: script: Update waiting for operator

- .github/workflows/pull-request-ci.yaml
This gives us ~double the memory, but half of the CPU (at a bit over half the price).  We appear to be memory-constrained; we're getting kubelet-level OOMs.
This bumps the memory on the cluster to 32GB (instead of the previous 16GB); to control costs, I have also reduced the CPU from 16 to 8.
🐱 runs were failing on GitHub Actions; hijacking a running test cluster show that the node had events that looked suspicious:
> `System OOM encountered, victim process: log-cache, pid: 123378`
Ran more 🐱 tests on my fork.  Double checked to make sure the duration of the steps were not too far off.  The only major difference is `make kubecf-wait` now takes ~18 minutes (out of a limit of 30).  In general though this _is_ slower: previously the pipeline took ~90 minutes, it now takes ~120.
> feat: CI: change instance type to standard-8

- .github/workflows/pull-request-ci.yaml
This attaches the (sanitized) owner name to the cluster name; this does _not_ remove the existing owner label on the cluster.
This is necessary because we don't get any information other than the cluster name with looking through DNS record sets; so we need something there to be able to identify entries that are safe to remove.
Deployed locally a few times (via GitHub Actions, of course).
> fix: CI: Add owner name to cluster name

- chart/config/releases.yaml
Not sure what happened to the postgres 42 image, but it doesn't seem to be there anymore.
Doing any deployment is now failing (because the postgres 42 release image is missing) when deploying with autoscaler.
Deployed locally.  Did not attempt smoke tests.
> fix: releases: bump postgres to 43

- bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch-cc.sh
- bosh/releases/pre_render_scripts/cc-worker/cloud_controller_worker/jobs/patch-cc.sh
- bosh/releases/pre_render_scripts/scheduler/cloud_controller_clock/jobs/patch-cc.sh
- chart/assets/operations/instance_groups/cc-worker.yaml
We can't bump capi-release right now until we also bump to Eirini-2.0.0.
Mitigates https://www.cloudfoundry.org/blog/cve-2020-5423/
> fix: backport YAML parsing fixes from CAPI-1.101.0

- bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh
- chart/config/releases.yaml
Bumps containerd to 1.4.3, which addresses CVE-2020-15257.
> fix: bump garden-runc to 1.19.17

- chart/hooks/pre-upgrade/remove-deployment-updater-readiness.sh
- chart/templates/hooks.yaml
- chart/values.schema.yaml
- chart/values.yaml
Adds a mechanism for hooking into the upgrade and deletion process of kubecf.
Removes the readiness probe for the CC deployment updater.
fixes #1589 
The readiness probe prevents the scheduler from being upgraded.
No local tests, waiting for the pipelines.
> feat: mechanism for hooking and fix for deployment updater upgrade

- chart/assets/scripts/jobs/pxc/functions.sh
- chart/templates/database/db-statefulset.yaml
- chart/values.schema.yaml
If the root password changes from under us (e.g. from a secret rotation), we need to tell MySQL about it so that things like the readiness probe will work with the new password.  A database seeder job will also be automatically triggered to take care of any of the other passwords changing.
Fixes #1355
- Deployed locally
- Manually deleted the database pod to make sure that recovers correctly.
- [Rotated](https://quarks.suse.dev/docs/quarks-operator/concepts/rotation_and_restart/#rotation) the `var-pxc-root-password` secret, to ensure that  we can update the root password correctly.
Probably should follow up to do the update-on-change thing; it didn't want to work for me…
> fix: PXC: Always reset the root password on start

- bosh/releases/pre_render_scripts/api/cloud_controller_ng/bpm/patch_bpm.sh
When the log-cache pod goes down, the gRPC endpoint used by CC goes down; it appears that the default c-ares DNS resolver used does not correctly recover when DNS successfully resolves again.  Switching to using the native DNS resolver instead appears to cause it to do proper exponential backoff instead, meaning that it will eventually recover.
This fixes issues where we become unable to restart applications after the log-cache role goes down; see #1547 for details.
- Started minikube
- Pushed an app (to ensure things are working)
- Scaled `log-cache` to 0 instances
- Restart the app (see issues about Statsd unavailable; this is expected)
- Scaled `log-cache` back up to 1 instance
- Wait a bit
- Restart the app, things work.
> fix: CC: use native DNS resolver for gRPC

- bosh/releases/pre_render_scripts/credhub/credhub/ig_resolver/patch_job_mf.sh
- chart/assets/operations/instance_groups/credhub.yaml
- chart/templates/_config.tpl
- chart/templates/_credhub.tpl
2 changes:
1. Disable the link via explicit nulling in the manifest. This part requires a quarks fix to work.
2. Patch the credhub spec with a ig-resolver pre-render script to remove the link from it.
Item 2 can be removed when quarks support item 1.
See #1649 
Minikube deployment, kubecf with autoscaler. Checked the resolved manifest for credhub to not use the postgres database.
> fix: prevent credhub from consuming the postgres bosh-link from auto-scaler postgres

- scripts/yamllint.sh
If the locale was set incorrectly, yaml linting will fail as the GitHub pipelines are using UTF-8.  As we can't guarantee Python 3.7 yet, we have to override `LC_ALL` rather than just set `PYTHONUTF8=1` (see PEP 540).
I had `LC_ALL=C` set for some insane reason, and linting was failing.
Ran `make yamllint` before & after changes.
> fix: lint: yamllint: force locale

- scripts/cf-operator-delete.sh
The cluster roles and role bindings are prefixed with `$CF_OPERATOR_RELEASE`.
Also, the names have changed, and there are 2 additional roles now.
> fix: update cf-operator-delete logic

- chart/hooks/pre-upgrade/remove-deployment-updater-readiness.sh
- chart/templates/hooks.yaml
kubecf with multi-az upgrade failed from version v2.6.1 to v2.7.1.
https://github.com/cloudfoundry-incubator/kubecf/issues/1662
run helm upgrade kubecf with the updated code, upgrade process moves on and all schedulers get upgrade successfully.
```
$ k get pod -n kubecf
NAME                                     READY   STATUS                  RESTARTS   AGE
api-z0-0                                 17/17   Running                 1          17m
api-z1-0                                 17/17   Running                 8          17m
auctioneer-0                             6/6     Running                 1          18m
bosh-dns-55f949b56d-6vbbq                1/1     Running                 0          4d20h
bosh-dns-55f949b56d-tgg5w                1/1     Running                 0 …
```
> fix: kubecf upgrade failure due to can't find multi-az scheduler

- chart/config/sle15.yaml
Image doesn't exist.
Reverts cloudfoundry-incubator/kubecf#1665
> Revert "feat: Bump suse-go-buildpack release to 1.9.24.1"

- chart/generate-minions-values.sh
- chart/templates/multiple_cluster_mode.yaml
- chart/values.yaml
Import CA certs of control plane to generate the certs required by diego-cell.
Add the CA certs instead of the certs that imported in the `credentials` in values yaml file. Those certs can be removed and  ca certs can generate those ones.
```
credentials_list=(
credhub_tls.ca
diego_bbs_client.ca
diego_bbs_client.certificate
diego_bbs_client.private_key
diego_instance_identity_ca.ca
diego_instance_identity_ca.certificate
diego_instance_identity_ca.private_key
diego_rep_agent_v2.ca
diego_rep_agent_v2.certificate
diego_rep_agent_v2.private_key
diego_rep_client.ca
diego_rep_client.certificate
diego_rep_client.private_key
forwarder_agent_metrics_tls.ca
forwarder_agent_metrics_tls.certificate
forwarder_agent_metrics_tls.private_key
gorouter_backend_tls.ca
loggr_udp_forwarder_tls.ca …
```
> fix: multiple-cluster-mode add ca certs required by diego-cell

- chart/hooks/pre-upgrade/remove-deployment-updater-readiness.sh
add a pre-check before patch scheduler statefulset during kubecf upgrade.
https://github.com/cloudfoundry-incubator/kubecf/issues/1675
This has been tested in kubecf v2.7.1, re-run helm upgrade, no incorrect patch to scheduler statefulsets.
```
$ k get pod -n kubecf
NAME                                     READY   STATUS      RESTARTS   AGE
api-z0-0                                 17/17   Running     16         3h49m
api-z1-0                                 17/17   Running     16         3h49m
auctioneer-0                             6/6     Running     1          3h50m
cc-worker-z0-0                           6/6     Running     0          3h49m
cc-worker-z1-0                           6/6     Running     0          3h50m
cf-apps-dns-59f9f659f5-c4z5g             1/1     Running     0 …
```
> fix: add pre-check on scheduler statefulset before patch it

- .concourse/pipeline.yaml.gomplate
Changes are bumps to sle15 and suse-java-buildpack, as well as a bump to quarks-operator-7.2.1
> fix: master into release-2.7

- chart/assets/operations/instance_groups/database.yaml
- chart/assets/operations/instance_groups/diego-api.yaml
- chart/assets/operations/instance_groups/locket.yaml
- chart/assets/operations/sequencing.yaml
- chart/assets/operations/sizing.yaml
- chart/config/jobs.yaml
- chart/config/resources.yaml
- chart/templates/_multicluster.tpl
- chart/templates/multiple_cluster_mode.yaml
- chart/values.yaml
Locket should be independant from diego-api.  Colocating them makes it less resilient and causes other instances to be incorrectly dependant on diego-api.
Moving the locket from diego-api to it's own pod.
It solves issues with diego-api being only able to talk to the single locket co-located.  It also allows for better separation of the two independant processes.
Fixes #1410
Deployed in IBM hybrid testing environments.
Can you point me to the docs I would need to update and I can add those to the PR.
> Split out locket from diego-api as it should be independant

- .concourse/pipeline.yaml.gomplate
Relevant changes:
* use `wait_for_kubecf` is more robust and doesn't return early
* don't deploy metrics-server chart if metrics-server is already running.
> Bump catapult to latest version

- bosh/releases/pre_render_scripts/scheduler/cc_deployment_updater/jobs/patch_cc_deployment_updater_erb.sh
- chart/assets/operations/instance_groups/database.yaml
- chart/assets/operations/instance_groups/scheduler.yaml
- chart/config/jobs.yaml
- chart/config/resources.yaml
- chart/templates/_capi.tpl
Add back the cc_deployment updater to the scheduler pod.
Basically this reverted commit dfcc97d441efab31ec49a07b3cf87062baf7aeac.  But also fixed the readiness check
This will allow the cc_deployment_updater to run and reenable the zero downtime functionality in CF.
Deployed this in a full kubecf env and ran the CATs tests which validate this functionality
> Renable cc_deployment_updater and fix readiness check

- chart/assets/operations/instance_groups/database.yaml
- chart/assets/operations/instance_groups/diego-api.yaml
- chart/assets/operations/instance_groups/locket.yaml
- chart/assets/operations/sequencing.yaml
- chart/assets/operations/sizing.yaml
- chart/config/jobs.yaml
- chart/config/resources.yaml
- chart/templates/_multicluster.tpl
- chart/templates/multiple_cluster_mode.yaml
- chart/values.yaml
Change #1697 was already merged to `master`, but I backed it out in #1725 because it looked like it might be responsible for the frequent upgrade-test failures on CI (even though it obviously passed CI itself before it was merged).
I think now that all the upgrade-test failures were due to the recently fixed catapult issues (and/or to running out of loadbalancers/firewall resources on GKE). This PR is just going to re-apply the original changes that were already merged before.
> Revert #1725 (i.e. re-instate #1697: split out locket into its own instance group)

- mixins/bits/config/bits.yaml
- mixins/bits/templates/bits.yaml
- mixins/eirini/config/eirini.yaml
- mixins/eirini/templates/deployment.yaml
- mixins/eirini/templates/events.yaml
- mixins/eirini/templates/metrics.yaml
- mixins/eirini/templates/routing.yaml
- mixins/eirini/templates/staging-reporter.yaml
- mixins/eirinix/templates/dns-aliases/deployment.yaml
Add setting of eirini/bits nodeselector configuration.
Add setting of eirini/bits nodeselector configuration. This follows the same pattern as the eirinix components where a nodeselector can be set for each component.
E.g.
https://github.com/cloudfoundry-incubator/kubecf/blob/master/mixins/eirinix/config/eirinix.yaml#L14
https://github.com/cloudfoundry-incubator/kubecf/blob/master/mixins/eirinix/templates/loggregator-bridge.yaml#L86-L87
Tested using updated kubecf helm chart v2.7.13. Set a node `xxx.xxx.xxx.165` with a test label and set the nodeselector to select that node.
> Add eirini/bits nodeselector
